### ISSUE TITLE
When users install the Kite atom plugin directly, drop them into the install flow

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#10]
When users install the Kite plugin directly, we should take them to the second step in the install flow where they enter their email address, we start downloading Kite, etc.  (We can skip the Kite-vs-Jedi screen.)

**Comment by abe33** [comment]
I was wondering whether we should use a unified UI from `kite-installer`, even in the plugin. I think it would help fixing issues such as #16, #17, and kiteco/kite-installer#28. What do you think?

**Comment by jtbarker** [comment]
+1 this, I have the kite plugin, but there is not yet a second step.  Very excited to get started as I got the invite!

**Comment by adamsmith** [comment]
Sorry for the long delay here, @abe33.  I think we should do what you suggest, and just skip the "Kite vs Jedi" step for people who install the Kite plugin directly.
