### ISSUE TITLE
Cannot change the kite settings

### ISSUE THREAD

**Issue by Xeoncross** [kiteco/atom-plugin#102]
Mac 10.11

Every action (typing or saving) opens up another dialog box which doesn't work:
 
![screen shot 2017-03-07 at 7 50 51 pm](https://cloud.githubusercontent.com/assets/56460/23686542/d982f41c-036f-11e7-8584-3e107c8747b4.jpg)

Clicking on the "setting" button opens a blank browser tab with: `http://local.kite.com:46624/settings/permissions?filename=[...]/sentence_matching.py&action=blacklist`

**Comment by jlozano** [comment]
Hi @Xeoncross sorry about that, we accidentally published a beta version of the plugin, if you update your kite plugin to v0.15.0 and restart atom and kite it should work
