### ISSUE TITLE
Stylize completion docs

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#103]
for completions from Kite:

* add a faint Kite logo in the bottom right, with an "Open in web" link to its left

* only allow documentation to render up to ~3 lines with roughly ~20 words per line?  (sorry not more precise; find something that you feel is right; the current issue is that even with doc strings truncated the docs area can get quite large)

**Comment by adamsmith** [comment]
![screen shot 2017-03-09 at 12 01 03 pm](https://cloud.githubusercontent.com/assets/87728/23768211/1b414240-04c0-11e7-9c32-27c85e08228c.png)

^ approx size of what I had in mind

**Comment by adamsmith** [comment]
it would also be useful to have an ellipsis at the end followed by a "more" link which would open up the sidebar/expand panel.

**Comment by abe33** [comment]
> add a faint Kite logo in the bottom right, with an "Open in web" link to its left

Not easily feasible, only markdown is supported, and all html code is escaped (hence why I didn't use the description_html until now), so we can't add buttons, or position elements using float. We can put an image but we'll have to do it using markdown so we can't control its size nor its position. And as we'll have to wrap the image in a link to produce the button we won't be able to target that link through CSS without polluting the styles of all the other links. 
But even if I had a way to add a link or a button with the logo, there's no information in a suggestion returned by kited that allows me to generate a link to that symbol/value.

> only allow documentation to render up to ~3 lines with roughly ~20 words per line?

It's hard to think in term of words and lines given that the box is resized based on the returned suggestions. I can truncate around 240 chars (3 lines * 80 chars) but that's the best that is achievable in HTML. Truncation and ellipsis are so complex that browsers only supports ellipsis on a single line and attempts to get multiline ellipsis standardized have all failed until now. 

> it would also be useful to have an ellipsis at the end followed by a "more" link which would open up the sidebar/expand panel.

It's the same issue as with the open in web link in a suggestion's description, without knowing the id of the value I can't expand it into the sidebar.

**Comment by adamsmith** [comment]
Sorry I should have specified, we'd like to monkeypatch autocomplete-plus to achieve this.  (as before we should do it in a way that won't cause odd behavior if autocomplete-plus has breaking changes.)

RE the max size, I worked some more with Antonio on this.  for the CSS of `autocomplete-suggestion-list.select-list.popover-list .suggestion-description` we'd like to add a `max-width: 600px`.  (for some reason autocomplete-plus specifies its sizes in px not rem, so we should probably follow that pattern.)

RE max lines, we suggest adding the following to `autocomplete-suggestion-list.select-list.popover-list .suggestion-description-content`: 
```
overflow: hidden;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
```

RE the links + logo, we suggest adding a block element after the `.suggestion-description-content` with essentially the same thing as the second line of the hover panel (this is a little different than what the original issue description asked for), i.e. "<a>def</a> <a>web</a> <a>more</a> [logo]".

RE the web link, Alex recommends using `completion.symbol.value[0].id`.  (if there are cases where this isn't there then we can skip adding the second row/div.)

**Comment by abe33** [comment]
> the web link, Alex recommends using completion.symbol.value[0].id. (if there are cases where this isn't there then we can skip adding the second row/div.)

As I said there's is no data I can use, no `symbol` field. The only fields I get are: `display`, `insert`, `hint`, `documentation_text`, `documentation_html`.

**Comment by abe33** [comment]
So, I found a simple way to patch autocomplete to get HTML description, that will also allow us to add custom buttons to that view. But I still can't find any other fields beside those I mentioned above so I can't implement any of these actions atm.

**Comment by adamsmith** [comment]
@abe33 , @dhung09 said he will add the `symbol` field to completions today.
