### ISSUE TITLE
small panel doesn't go away after editing/cursor out

### ISSUE THREAD

**Issue by intrepidlemon** [kiteco/atom-plugin#105]
![image](https://cloud.githubusercontent.com/assets/6819750/23780781/c11cc882-04fd-11e7-9c2e-6f5b6a14366f.png)

This hover panel is sometimes sticky and doesn't go away even after clicking outside of the box.

**Comment by abe33** [comment]
Hi @intrepidlemon, do you have some steps that would allow me to reproduce that issue?

**Comment by intrepidlemon** [comment]
I'm having difficulty reproducing this myself. I can just close it for now. thanks @abe33
