### ISSUE TITLE
Whitelisting modal disappears and reappears on each keystroke

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#114]
Steps to reproduce:

1) open non whitelisted file `foo.py`
2) Click `Settings` and then click `Blacklist ../foo.py`
3) go to `localhost:46624/settings/permissions` and remove the suppressed directory from step 2) from the blacklist (Suppressed Prompts section)
4) go back to `foo.py` the whitelisting modal disappears and reappears on each keystroke

Seems like it might have something to do with only ever showing one modal at a time?

**Comment by abe33** [comment]
I wasn't properly using my map of last displayed notifications, so instead of preventing any new notification it was creating a new one while dismissing the old one.
