### ISSUE TITLE
Better logic for finding the right directory to whitelist

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#12]
See https://github.com/kiteco/atom-plugin/blob/4baea65c4ddd5febc5bff58d46a8f82188d1a65f/lib/ready.js#L393

Currently we use the parent directory, which is a really poor heuristic because most .py files will be in a project nested under several levels of hierarchy, so the user would have to keep whitelisting tons of dirs.

Instead we should do the following:

1. Look for the first parent directory to contain a .git folder, and if it exists, use that as the directory to suggest whitelisting.
2. If that doesn't exist, look for the parent directory / project directory in Atom, and suggest using that.
3. If that doesn't exist, and the current file is under `~` (the user's home directory), suggest whitelisting the user's home directory (but list it as the fully qualified path, e.g. `/Users/foo`, and not `~`).
4. If `.git` and parent root aren't possible, and it's not under `~`, suggest whitelisting `/`.

**Comment by abe33** [comment]
I would suggest to use the `atom.project.getPaths()` method. It'll generally match the git root directory as it's how most people is using Atom (through `atom .` in the project root directory) but it'll also help whitelisting all the directories in the case of a multiple directories project. And it will still work if the project is using mercury or any another version control platform.

**Comment by adamsmith** [comment]
Okay, sounds good, we could skip the first step.

**Comment by adamsmith** [comment]
Fixed by Cedric.
