### ISSUE TITLE
Scrollbars in completions UI

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#121]
This is on 0.20170314.1 and 0.16.0.

<img width="383" alt="screen shot 2017-03-14 at 9 00 36 pm" src="https://cloud.githubusercontent.com/assets/87728/23933117/9b4dd308-08f9-11e7-9210-718b413f1b3c.png">

(Is this related to the max-width css we discussed last week?)

**Comment by abe33** [comment]
I'm not really sure, I never had this issue on OSX, is that on windows?
