### ISSUE TITLE
Call signatures will not show up until you delete the open parens and type it again

### ISSUE THREAD

**Issue by keien** [kiteco/atom-plugin#134]
e.g. in new python file, type (`|` is cursor)
```
import requests
requests.post(|
```
there's no call signatures

then hit delete so current line is
```
requests.post|
```
then type `(` again - now the call signatures show up

**Comment by abe33** [comment]
There's several factor for that issue:
- in some circumstances the signature endpoint takes more time that completions, and in that case the signature element wasn't properly added into the autocomplete panel, that's now fixed
- the endpoint randomly returns `410` errors so we don't get any call signature to display

**Comment by jlozano** [comment]
@keien are you still experiencing this issue?

**Comment by keien** [comment]
does not seem so

**Comment by abe33** [comment]
Ok cool, I'll close the issue then.
