### ISSUE TITLE
Clicking on a usage doesn't work if there are url escaped chars in the path

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#135]
Jumping to a definition doesn't work here:

<img width="455" alt="screen shot 2017-03-20 at 9 14 21 pm" src="https://cloud.githubusercontent.com/assets/87728/24132364/4752f8d8-0db2-11e7-894b-80ba7bb5ddf0.png">

**Comment by adamsmith** [comment]
Seems to be fixed in the latest.  (sorry about that!)

**Comment by adamsmith** [comment]
Actually, sorry, it looks like this is an issue when clicking on a Usage in the side panel.  (but "def" in hover works)

**Comment by adamsmith** [comment]
[this isn't for the demo video]

**Comment by abe33** [comment]
Should be fixed now, I wasn't properly decoding the path from internal urls.
