### ISSUE TITLE
Plan is cached

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#136]
@abe33 it looks like we are caching the plan object in the plugin? This can be problematic because if the user starts their pro trial or purchase pro from the website they have to restart atom before they see pro results.

**Comment by jlozano** [comment]
@abe33 I am still getting this issue, steps to repro:

1) `$` is the cursor
```
import os
os.path.join($)
```

2) i get which is correct
![screen shot 2017-03-21 at 6 57 19 pm](https://cloud.githubusercontent.com/assets/425691/24178739/40ca9398-0e68-11e7-890c-d756f6854ef7.png)

3) I hit start trial and my trial is started

4) delete `os.path.join`
```
import os
$
```
5) retype `os.path.join($)`

6) still see start trial call to action
![screen shot 2017-03-21 at 6 58 50 pm](https://cloud.githubusercontent.com/assets/425691/24178775/6eeb05aa-0e68-11e7-85a4-911822b7c4f9.png)

7) same thing happens if I add `import json; json.dumps()`

8) 
```
import os
os.path.join()
import json
json.dumps($)
```

9) i get 
![screen shot 2017-03-21 at 7 00 43 pm](https://cloud.githubusercontent.com/assets/425691/24178817/b42339a8-0e68-11e7-8fc0-d2b8b30e7fda.png)

Is it possible to refetch the plan on each call to `Plan.can` ?

**Comment by jlozano** [comment]
@abe33 I added to endpoints that can be curled to set the plan state:

`curl -X PUT localhost:46624/clientapi/manual-plan?startPlan=start&localtoken={localtoken}` will update the plan in `kited` to the "has access to pro via a trial state"

`curl -X PUT localhost:46624/clientapi/manual-plan?endPlan=end&localtoken={localtoken}` will update the plan in `kited` to "has no pro access and has used trial state"

please only use this endpoint via `curl`

**Comment by abe33** [comment]
> Is it possible to refetch the plan on each call to Plan.can ?

Not really, I need `Plan.can` to be synchronous otherwise I'll have to rewrite a huge chunk of the plugin.

There was a bug in the plan object, I thought I add removed the cache but it seems I only did that in my status panel PR. But event then, when calling the curl enpoint to start the trial I still receive a community plan with `common_invocations_editor` at `false` which explains why we don't see the common invocations after the change.

**Comment by jlozano** [comment]
> Not really, I need Plan.can to be synchronous otherwise I'll have to rewrite a huge chunk of the plugin.

Got it.

> There was a bug in the plan object, I thought I add removed the cache but it seems I only did that in my status panel PR.

This appears to have fixed it as it is now working on my machine with current version of master. Closing this
