### ISSUE TITLE
add "def" and "more" links to call sigs (in addition to "more")

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#142]
("def" only where applicable, i.e. for local code)

<img width="520" alt="screen shot 2017-03-23 at 8 16 16 pm" src="https://cloud.githubusercontent.com/assets/87728/24279209/b3817f34-1005-11e7-83f4-edd7ae37d3c6.png">

**Comment by abe33** [comment]
So I have a first implementation that works pretty much like the hover and completion ones (actually I refactored these parts as well to use the same underlying component).

But there's two big issues with the current signatures data:
- there's no definition field, so I must use the id to get the definition through the report endpoint
- as I'm using the id, we get the same issue as with hover links, if the id is empty we can't find a definition for it.
