### ISSUE TITLE
remove "atom - completion in function call" Mixpanel event

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#145]
I hate to be pulling events from the plugin but it seems like this is getting used too much  : /

thanks!

**Comment by adamsmith** [comment]
Same with `atom - signature shown in autocomplete-plus`

Please only keep, or add, events for when users do something explicitly in Kite (click on a Kite link, open a Kite panel, etc).

**Comment by abe33** [comment]
Should be good, I added a custom, hidden, setting you can set through the console to just see metrics debug (using `atom.config.set('kite.debugMetrics', true)`), lmk if you see other metrics to :fire:

**Comment by adamsmith** [comment]
Thanks! : )
