### ISSUE TITLE
Atom does not recognize that Kite is installed

### ISSUE THREAD

**Issue by flaviomeira** [kiteco/atom-plugin#148]
After install Kite, via package installation on Atom, the icon appears on the bottom of the window with the message 'Kite is not installed'.
PS: My SO is Windows 10 x64.

**Comment by adamsmith** [comment]
Hi @flaviomeira, trying to chase this down: does it stay this way even if you edit a .py file thirty seconds later?

**Comment by abe33** [comment]
Also, is there any error message in the devtools console? Do you still get that issue after a restart?

**Comment by Croozer-IoT** [comment]
I have the same issue. in the right lower Corner is a red kite wit the lable  "Kite is not installed"

History:
I installed Atom a day before and kite worked well (ask for path to add, if I import new .py files from different HDs)
I had to deinstall Atom and reinstall. after the new Installation Kite didn't work (ask not for path, red kite)
I do 3 time reinstallation, without success.

Win 10 64bit

**Comment by abe33** [comment]
@flaviomeira @Croozer-IoT: I just published a patch that should fix the issue, let me know if you still get any issue.

**Comment by ravi1-7** [comment]
> After install Kite, via package installation on Atom, the icon appears on the bottom of the window with the message 'Kite is not installed'.
> PS: My SO is Windows 10 x64.

I've got the same issue. I have reinstalled kite and atom multiple times yet I'm getting the same error message of "kite engine not installed" though atom says the kite package has been installed. I'm using macOS Catalina
