### ISSUE TITLE
Parameters in expand panel take up too much space

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#152]
Probably allow the function signature to wrap multiline and then don't show the Parameters section, especially when there are no docs for any of the params.

**Comment by abe33** [comment]
Like this?

<img width="400" alt="kite-sidebar_less_ ___github_kite_et_main_window" src="https://cloud.githubusercontent.com/assets/247140/24558880/006f7e76-163d-11e7-87dc-4808423205a6.png">

The downside being that if we have a long parameters list and a return type it gives a weird layout:

<img width="415" alt="sample_py_ ___github_kite" src="https://cloud.githubusercontent.com/assets/247140/24559025/85d673bc-163d-11e7-9b15-6459b1e4e527.png">

**Comment by adamsmith** [comment]
for the multiline case, can we:

* move the return type to the "middle", e.g. in the case above it would be offset by half a line
* make second+ lines on the left have a small amount of indentation, so it's easier to see that it's wrapped text?
