### ISSUE TITLE
Failed to load the kite package

### ISSUE THREAD

**Issue by IanVermes** [kiteco/atom-plugin#156]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.20.2

### Stack Trace

Failed to load the kite package

```
At '../node_modules/kite-installer/styles/styles.less' wasn't found in /Users/Ian/.atom/packages/kite/styles/kite.less:2:0

LessError: '../node_modules/kite-installer/styles/styles.less' wasn't found
  at /packages/kite/styles/kite.less:2:0
```

### Commands

```
     -0:31.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-native-ui)
```

### Non-Core Packages

```
autocomplete-python 1.8.63 
busy-signal 1.3.0 
file-icons 2.1.2 
intentions 1.1.2 
kite 0.20.2 
linter 2.1.2 
linter-pylint 2.0.1 
linter-ui-default 1.2.2 
native-ui 0.20.4 
Pompomodoro 1.0.0 
unity-ui 2.1.10 
```

**Comment by IanVermes** [comment]
Issue appears on startup of Atom with Kite having started in the background before hand.

**Comment by abe33** [comment]
Hi @IanVermes, can you see the corresponding file in the package's directory?
