### ISSUE TITLE
Unable to start Kite engine

### ISSUE THREAD

**Issue by gdenn** [kiteco/atom-plugin#159]
I receive an error when i install the kite plugin version 0.20.2 in my atom editor version 1.15.0 x64. My System is a MacBookPro 10.1 . My OSX version is 10.12.3 MacOS sierra.

I can install the kite plugin. After activating the plugin i receive the message (in atom editor) to activate the kite engine. I click "start" and receive the following error:

```
Unable to start Kite engine

{"data":""}
```

Here is a screenshot of the error popup:

<img width="496" alt="screenshot 2017-04-07 09 13 01" src="https://cloud.githubusercontent.com/assets/9344404/24789275/8ac3a798-1b72-11e7-815a-ece9ceba8dc7.png">

cheers,
Dennis

**Comment by abe33** [comment]
Hi @gdenn, are you able to start `/Applications/Kite.app` manually?

**Comment by jlozano** [comment]
@abe33 I also observe this running Mac OSX 10.11.4 and Atom 1.17.2 using Kite app 20170601.0 and
