### ISSUE TITLE
kite is unknown state -1

### ISSUE THREAD

**Issue by Yuzeyang** [kiteco/atom-plugin#160]
Atom: 1.13.0
macOS: 10.12.4

i install kite in Atom, but kite notice 'kite is unknown state -1', and it cannot work

**Comment by abe33** [comment]
Hi @Yuzeyang, Have you tried to restart Atom? It happens that Kite's daemon doesn't respond right away.

**Comment by Yuzeyang** [comment]
i restart my mac, kite can work now, thanks~
