### ISSUE TITLE
Add permissions to command palette

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#166]
Add an `Open Permissions` item to the command palette, this item should always be the first in the list when the user types `kite`

![image](https://cloud.githubusercontent.com/assets/425691/24987844/f44de974-1fb6-11e7-9d3e-849a90a161e2.png)

**Comment by abe33** [comment]
I can add the command, but there's no control over the items sorting, it depends on the fuzzy match algorithm.

**Comment by jlozano** [comment]
got it, makes sense!

**Comment by jlozano** [comment]
Nice!
