### ISSUE TITLE
Unable to install kite engine through atom

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#170]
Me: Running Atom 1.16, Kite Atom Plugin 0.21.1, mac OS X 10.11.4, I see the following error report:
![screen shot 2017-04-18 at 5 57 02 pm](https://cloud.githubusercontent.com/assets/425691/25158907/b5a45416-2460-11e7-8332-cb28dc356043.png)

Caleb: Running Atom 1.16, Kite Atom Plugin 0.21.1, macOS 10.12.4, he sees the following error report:
<img width="574" alt="atom-install" src="https://cloud.githubusercontent.com/assets/425691/25158937/f3c2cd9a-2460-11e7-866e-c2808e6bd768.png">

**Comment by jlozano** [comment]
from mixpanel it looks like we had a spike of them on Wednesday april 13th: https://mixpanel.com/report/781687/segmentation/#action:segment,arb_event:'atom%20-%20install%20failed',bool_op:and,chart_analysis_type:linear,chart_type:line,endpoint:segmentation,from_date:-365,graph_params:(event:'atom%20-%20install%20failed',from_date:-365,to_date:0,type:unique,unit:week),ms_checked:('atom%20-%20install%20failed':!t),ms_values:!('atom%20-%20install%20failed'),to_date:0,type:unique,unit:day

**Comment by abe33** [comment]
I tried to further research this issue, but I couldn't find a comprehensive explanation as to what triggers it. It looks like some random low level issue with the https layer in node, because we never hit localhost:443 directly.
