### ISSUE TITLE
How to get autocompletion and code fixes in Kite: Open Sidebar to work?

### ISSUE THREAD

**Issue by hugeme** [kiteco/atom-plugin#175]
ATOM: 1.16.0
MAC 10.12.03

Hi,

thanx for deepen the kite atom integration.

However, Im not fully understand how that plugin works. After seeing that video:
https://www.youtube.com/watch?v=YkXzAbO2sHg

I have expected that kite:

- show function signature based on popularity
- detecting errors
- autocompletion
- Interaction with terminal
- Documentation

Documentation I can use over Side bar and Active Search or when hovering over some code. Function signatures I can get by calling corresponding functions. However, I assumed that the Side bar in Atom takes the role of KiteSidebar.
In the first picture you see as I have both open the KiteSidebar(app which I have brew installed) and the Side bar I have called from inside Atom `Kite: Open Sidebar`.  In Atom the Side bar displays only the documentation as shown in the second picture, nothing else:

![test](https://cloud.githubusercontent.com/assets/18237090/25637029/b5a41478-2f83-11e7-87ab-a204c62327a1.png)

![sidebar](https://cloud.githubusercontent.com/assets/18237090/25637419/302c02a4-2f85-11e7-8e75-e2cfa522902d.png)

Therefore Im not sure whether I have missed something or some parts are not included yet. 

How can I use Atom Side bar via `Kite: Open Sidebar` instead of KiteSidebar (app)?

Appreciate any suggestions!

**Comment by jlozano** [comment]
@hugeme sorry for the confusion!

- The atom sidebar is not meant to replace the kite sidebar, rather it is used to expand information about a given identifier to allow deeper dives. 

- Completions, popular patterns (function signatures) should now appear under your cursor.

- Automatic error correction is currently only available in the kite sidebar app, there are no plans to port this to the editors in the near future.

- Terminal integration is currently disabled for performance reasons, we will hopefully add it back in the future.

Hope this helps!
