### ISSUE TITLE
Status panel tweaks

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#178]
@abe33 
- we added to more states for the status, `Kite is indexing your code` and `Kite is syncing your code`, they should both have the same blue icon that we show when the plugin is functioning normally. The status can be retrieved from `/clientapi/status`, see here for api: https://kite.quip.com/jJdMAx2b8OsT#AaQACANNDrD

- we added the information on user's referrals to the response from `/clientapi/plan` so that we can implement the "invite" calls to action, see here for api: https://kite.quip.com/PgOaAiA5GUUM.

full design doc: https://www.dropbox.com/s/0vlmqw9bws0sbiy/PluginsAudit_April2017-02.jpg?dl=0
api doc: https://kite.quip.com/rVcJA1bIqZny

**Comment by jlozano** [comment]
@abe33 nice work!

**Comment by jlozano** [comment]
@abe33 one minor thing, the link for the "Referral Status" to "Invite more people" should link to `localhost:466234/redirect/invite`. https://kite.quip.com/rVcJA1bIqZny#QcWACAfPRvB

**Comment by abe33** [comment]
1. I believe the current url is correct, or did I miss something? https://github.com/kiteco/atom-plugin/blob/master/lib/elements/kite-status-panel.js#L229

**Comment by jlozano** [comment]
@abe33 weird, will double check today, that link is correct, not sure what i saw yesterday.

**Comment by jlozano** [comment]
@abe33 confirmed 1 is the correct url, sorry about that. confirmed 2 and 3 are fixed, great work on this!
