### ISSUE TITLE
Atom docks

### ISSUE THREAD

**Issue by yochem** [kiteco/atom-plugin#184]
7 Days ago, Atom released a new version ([1.17.0](https://github.com/atom/atom/releases/tag/v1.17.0)). This new version includes a new atom element named [docks](https://github.com/atom/atom/pull/13977). Maybe the treeview dock is a good place for the search menu, which for now is on the right side of the screen (on top of the minimap package). Hope you see a future in this new atom function. :)

**Comment by abe33** [comment]
That's an interesting suggestion, I haven't played much with docks yet, but I'll try experimenting with that and we'll see how it can be supported.

**Comment by hughcameron** [comment]
+1 to this! The dock would be a great place for the Kite sidebar to live.

**Comment by abe33** [comment]
This is now available through a setting 🎉
