### ISSUE TITLE
Error when starting kite from atom

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#190]
@abe33 no errors appear in the console, is there another way I can provide debug info?

![screen shot 2017-05-26 at 4 03 00 pm](https://cloud.githubusercontent.com/assets/425691/26515670/de977e54-4231-11e7-9523-91d93d9915a2.png)

**Comment by abe33** [comment]
Hi @jlozano, I'm using the `stderr` content as the output for `data` so I'm not sure what additional info I can provide in that case. If the errors occurs before the process creation (in the node part that is), the error is caught inside the promise and should appear as the rejection message.

**Comment by jlozano** [comment]
duplicate, closing
