### ISSUE TITLE
Sticky headers not scrolling all the way to the top

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#194]
@abe33 As I understand it the sticky headers should scroll all the way to the top and not show the text moving between the headers?

https://cloud.githubusercontent.com/assets/87728/26607023/3c219108-4549-11e7-9f2d-12d78d3a5194.gif

**Comment by abe33** [comment]
Is that occuring systematically?

**Comment by jlozano** [comment]
@abe33 I have not been able to reproduce it reliably, @adamsmith do you see this consistently?

**Comment by adamsmith** [comment]
It reliably repros on my machine.  (El Capitan and Atom 1.17.2)

**Comment by abe33** [comment]
Hmm, it might be related to how Chrome is handling fixed elements offsets. Normally, fixed elements are positioned relatively to the whole document, but in recent chrome version it seems they are positioned relatively to the nearest parent with either an absolute or relative position. I'll probably have to make some version check to make sure I handle both cases.

**Comment by abe33** [comment]
Weird, I don't reproduce on 1.17.2, I'm on Sierra but I don't really see why it could have an impact on this kind of stuff.
