### ISSUE TITLE
Kite tour updates

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#196]
@abe33 we want to create more room for the scrolling region of the kite tour, what do you think of the following changes?
- Make Kite logo at top smaller.
- Move kite Logo next to the header text and make the header text have smaller font.
- Move the `Kite is your Coding Copilot` text to be part of the scrollable region and have it at the bottom.

The goal is to make the scrollable area atleast 70% of the height of a reasonably sized window.

**Comment by abe33** [comment]
With the new version, for a container height of ~615px I get a scrollable area that takes ~70% of the whole height: 

![kite-tour](https://cloud.githubusercontent.com/assets/247140/26684967/01091086-46e9-11e7-8c8c-6103578216be.gif)
