### ISSUE TITLE
Design pass 2

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#200]
@abe33 great work on the first design pass! We did another pass today, let me know if anything doesnt make sense!

## Expand Panel
- [ ] 1) Sticky headers
  - [x] 1a) (TODO @abmirayo to add mockups)
    - Update: https://www.dropbox.com/s/s0oaym290d4qbjx/PluginsAudit_April2017Rev3.jpg?dl=0
  - [ ] 1b) Decrease spacing between headers so that you do not see text and whitespace flashing between headers as you scroll.

- [x] 2) Usages
  - [x] 2a) Switch title from `Usages` to `Usages from your code`
  - [x] 2b) Put usages above examples

## Live signature panel
- [x] 1) The default arguments are not being shown correctly (TODO @dhung09) (see `b` keyword arg in gif):
![atom-should-highlight-kwargs-index](https://cloud.githubusercontent.com/assets/425691/26711953/ce49262e-4718-11e7-99ae-f3693f41a76b.gif)

- [x] 2) Set max width of panel to 30 em
- [x] 3) Wrap popular patterns by token instead of adding scrollbar

- [x] 4) `**kwargs`
  - [x] 4a) Can't click on the`**kwargs` link when you are typing an argument:
![atom-patterns-unresponsive](https://cloud.githubusercontent.com/assets/425691/26711490/7007839c-4715-11e7-80cb-b82e32e74a8c.gif)
  - [x] 4b) Once `**kwargs` are expanded you cannot type anymore
  - [x] 4c) If the user is typing an argument that matches a `**kwarg` then expand the `**kwargs` section and highlight the argument. This information is included in the response, (note that the `in_kwargs` field is true and the index is relative to the `**kwargs` not the standard args when the user is typing an argument that matches a `**kwarg`):
![atom-should-highlight-kwargs-index](https://cloud.githubusercontent.com/assets/425691/26711467/4c0fbc5c-4715-11e7-8bc1-9283fe0417c5.gif)
   - [x] 4d) Popular patterns disappear when typing an argument (looks like we maybe switch to completions?): 
![atom-patterns-unresponsive](https://cloud.githubusercontent.com/assets/425691/26712098/c7ecc6e0-4719-11e7-9a0a-9884d4c5c0df.gif)

## Status panel
 - [x] 1) Always show invite others call to action in the [menu section]( https://kite.quip.com/rVcJA1bIqZny#QcWACArvrDW)

- [x] 2) Remove [notification for referral credits](https://kite.quip.com/rVcJA1bIqZny#QcWACAfPRvB) (sorry about this we will add it back when we have a proper notification system in place on kited + user-node).

- [x] 3) When the user is logged out or kited is not running:
  - [x] 3a) Gray out (and disable) all [menu items](https://kite.quip.com/rVcJA1bIqZny#QcWACA3Hd3y) except help item. 
  - [x] 3b) Do not show the verify email notification or any Account status or notifications

- [x] 4) Use smaller assets (TODO @abmirayo to add links)

  - Update by @abmirayo (These Kite logos should be used for status icons and other places where the logo is pretty small): https://www.dropbox.com/sh/fdl9g3yqadtr2nt/AACJ0hKNK8flURUNhCXOyeQba?dl=0

- [x] 5) Use windows specific gift asset for [invite call to action](https://kite.quip.com/rVcJA1bIqZny#QcWACArvrDW) on windows (TODO @abmirayo to link to asset)

  - Update by @abmirayo: https://www.dropbox.com/sh/o5nxnt2qjs5eeue/AADb6sl2zLHULQY7WYnfYPifa?dl=0

## Status panel icon
- [x] 1) Use the red icon when the user is logged out.
- [x] 2) Use the "syncing/indexing" [icon](https://www.dropbox.com/s/c1dktvm0e87hdy6/PluginsAudit_April2017-07.jpg?dl=0) for the indexing/syncing states. assets:  https://www.dropbox.com/sh/fdl9g3yqadtr2nt/AACJ0hKNK8flURUNhCXOyeQba?dl=0

**Comment by abe33** [comment]
About the syncing/indexing status panel icon, do you see a better strategy than polling the status endpoint until I get a `ready` status?

**Comment by abe33** [comment]
1b) Another case of chromium weirdness, depending on the version and OS it seems to give different measurements (I must measure nodes to place them correctly) and, maybe I can workaround that by rounding below values whenever I measure something.

**Comment by abe33** [comment]
Live signature 3) I'm not sure to understand what you mean by "Wrap popular patterns by token", can you elaborate?

**Comment by abe33** [comment]
Status panel 1) Even when on an enterprise account?

**Comment by jlozano** [comment]
@abe33 
> About the syncing/indexing status panel icon, do you see a better strategy than polling the status endpoint until I get a ready status?
Unfortunately no, but the poll interval can be pretty long, e.g 30 seconds to a minute is probably fine. In the future we may set up a system for kited to "push" events to the editors.

> 1b) Another case of chromium weirdness, depending on the version and OS it seems to give different measurements (I must measure nodes to place them correctly) and, maybe I can workaround that by rounding below values whenever I measure something.
Damn, that is tricky, if the work around gets ugly or makes the code fragile we can revisit this.

> Live signature 3) I'm not sure to understand what you mean by "Wrap popular patterns by token", can you elaborate?
Yup, I meant that we should wrap the popular patterns the same way that we wrap the arg spec, based on the tokens (e.g `encoding`, `default`, `indent` see image below) instead of on a per character basis, does this make sense?
![screen shot 2017-06-02 at 12 09 01 pm](https://cloud.githubusercontent.com/assets/425691/26740907/46139888-478c-11e7-97b2-7c27dec8093f.png)

> Status panel 1) Even when on an enterprise account? Or when not logged in ?
Sorry should have clarified, no for the enterprise account, and show it as grayed out when the user is logged out or kite is not running.

Let me know if this all makes sense!

**Comment by abmirayo** [comment]
I've added links in the description above, and the mockup: 

![pluginsaudit_april2017rev3](https://cloud.githubusercontent.com/assets/163122/26797375/942eb2c6-49e1-11e7-9b73-dfd83ec2e55b.jpg)

**Comment by abe33** [comment]
@jlozano Oh, I get it, sorry, I was somehow confused, not sure why though. That should not be an issue then, however point 2 (Set max width of panel to 30 em) might be more problematic, as we're hooking on the autocomplete-plus panel I'll need to make sure that it won't create issue when there's some completions.

**Comment by abe33** [comment]
Here's what I get with the 30em limit and proper word wrapping.
<img width="512" alt="sample_py_ ___github_kite" src="https://cloud.githubusercontent.com/assets/247140/26833404/9e8ca362-4ad2-11e7-9077-cece6c2bfde5.png">

**Comment by abe33** [comment]
4d) Actually that was a choice made early in the project because it was taking a lot of vertical space, that can be easily turned off if needed.

**Comment by abe33** [comment]
Live signature panel 1) That's fixed, I'm now using the `repr` field but I noticed that for a function like `foo(arg=True)` the `repr` for `arg` default value is `bool` and not `True`, is that expected?

**Comment by jlozano** [comment]
@abe33 
- 30 em looks good!
- 4d lets turn it off and ill test it out!
- for the default argument not showing true i have added a github issue
Let me know when i should test!

**Comment by jlozano** [comment]
@abe33 as discussed in real life, we can ignore issue 1b for now.

**Comment by jlozano** [comment]
@abe33 As discussed in real life, we will figure out the completions issue in a separate branch.
