### ISSUE TITLE
Only show "start kite" popup once

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#212]
@abe33 
Can we just show the popup once per user session, e.g we show it once on atom startup and then don't show it again until they quit atom and restart it?

Thanks!

**Comment by abe33** [comment]
Hi @jlozano, I'm not really sure to understand the change with the current behaviour. We're actually showing it only once per session, as we're switching on a boolean flag for each notification that is only stored in memory and so will be reset on restart

**Comment by jlozano** [comment]
@abe33 perfect! closing.
