### ISSUE TITLE
Show arguments for constructor types

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#218]
We should display the arguments to type constructors the same way we should arguments to functions e.g. for `gevent.pywsgi.WSGIServer`:

![image](https://user-images.githubusercontent.com/3752225/28233140-93de7f36-68a9-11e7-8b7d-ea31a9f34bfe.png)

![image](https://user-images.githubusercontent.com/3752225/28233143-9ab63cd6-68a9-11e7-9965-727639840b52.png)

The constructor arguments are accessible via details -> constructor -> parameters.

I'm not sure if we made a conscious decision to not show them in the expand panel. If we did, then we don't have to show them there. But we should definitely show them in the signature.

**Comment by abe33** [comment]
Hi @dhung09, we're receiving `self` as the first argument, is it expected or should I ignore it for the time being?

**Comment by dhung09** [comment]
we should ignore the first argument for constructor because we currently return `self` (don't think this is changing anytime)

**Comment by dhung09** [comment]
actually @abe33 let's not skip it for now. after thinking about it a bit, it may be better for the backend to remove it before sending it to the plugins
