### ISSUE TITLE
Only show `def` link when both the filename and line number are set

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#220]
we should only show the `def` link when both the filename and the line number are set (note that the line number can be 0 for modules, but the filename should always be non empty).

**Comment by jlozano** [comment]
From @adamsmith 
```
(Though less important, the same thing applies to Atom's right click menu. If we can't dynamically show/hide this, then it'd be better when someone clicks "Kite: Go to definition" if we don't have it to show a message box instead of opening an empty tab.)
```

**Comment by abe33** [comment]
@jlozano There's a few remaining issues I can't directly address in the plugin: 
- let's say I have a `dummy` function defined and used in the same file. Hovering the function definition will give me a proper file name and line but it's useless given I'm already at the definition location. hovering one of its usage, though, won't give me a definition (`definition` is `null` in the hover data).
- For the right-click menu I can do nothing about it, everything is sycnhronous, so the visibility of the action can't be decided after an asynchronous call to `kited`. Currently I'm using the tokens provided by the `tokens` endpoint to decide whether to show the menus or not. I think I mentioned that issue at some point to Alex, the idea would be to have fields for each token to tell editors what can of information it can expect for that token, for instance a `hasDefinition` boolean would aloow me to show the right click menu only for tokens that have a definition.
