### ISSUE TITLE
Remove checkbox for "show kite tour" when installing via acp

### ISSUE THREAD

**Issue by jlozano** [kiteco/atom-plugin#221]
@abe33 since we now only show the tour once we can remove this check box and the option in the plugin (if we have not already).

**Comment by abe33** [comment]
I can remove the checkbox, but we're using the setting as our switch for the tour display, so Atom will still show us a checkbox in the plugin's settings form (Atom has a weird habit of also building inputs for fields that are in a user's config file but not declared in the corresponding plugin's config)
