### ISSUE TITLE
kite hangs during package installation

### ISSUE THREAD

**Issue by lucainnocenti** [kiteco/atom-plugin#224]
When I install kite on atom, I see the screen prompting me to choose my autocomplete-python engine and asks for my email to sign-in.
However, this loading screen stays there forever, and when I try to put an email and click `Continue` an error message occurs (and no email is sent):

![screenshot 2017-07-21 10 21 15](https://user-images.githubusercontent.com/10957113/28458113-7432cd02-6e00-11e7-9eb4-bbef5bdb27e2.png)

Here is also a screen of console when this happens, in case it is useful:

![screenshot 2017-07-21 10 36 54](https://user-images.githubusercontent.com/10957113/28458296-28957b50-6e01-11e7-8554-b706e21dcf88.png)

In the atom package list kite is listed as installed, but then if I close the above installation window and restart atom, the same issue arises again.
In the bar on the bottom of the windows there is the small kite symbol, but is in red and says that kite is not installed on hover.

I experience this on macOS Sierra 10.12.6, atom 1.18.0 x64, kite 0.30.1.
Here is the content of `.atom/packages`:

```
Hydrogen
MagicPython
README.md
autocomplete-python
busy-signal
git-plus
goto-definition
goto-mathematica
hyperclick
intentions
kite
language-latex
language-markdown
language-mathematica
last-cursor-position
latextools
linter
linter-mathematica
linter-pylama
linter-python-pep8
linter-ui-default
markdown-preview-plus
minimap-plus
python-debugger
python-indent
python-tools
```

**Comment by bcurtiswx** [comment]
Confirmed on windows 10, atom 1.19.0 x64, kite 0.33.0.

**Comment by jansorg** [comment]
@lucainnocenti @bcurtiswx We fixed an issue with the installation and download. Please reopen if you're still experiencing this!
We're sorry for this very late reply.
