### ISSUE TITLE
Removing current configs

### ISSUE THREAD

**Issue by windhamwong** [kiteco/atom-plugin#229]
The plugin removes all the user's sidebar settings. That is not a good way to deploy software. Please fix it or get down voted.

**Comment by abe33** [comment]
Hi @windhamwong, I'm not sure to understand exactly what you're experiencing, would you be kind enough to elaborate a bit on what's happening?

**Comment by jansorg** [comment]
@windhamwong Please reopen this if you're still thinking that this is related to the Kite plugin. Please provide a bit more context to help us to address this. Thanks!
