### ISSUE TITLE
Top members links should be using /api/editor/symbol instead of /api/editor/symbol

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#230]
Clicking on all top members in the expand panel results in 404's. This is because that interaction is using the `/api/editor/value` endpoint, but should be using the `/api/editor/symbol` endpoint

**Comment by abe33** [comment]
Hi @dhung09, that's weird actually, I never experienced that (see below), can you point me to a module that triggers that for you so I can try reproducing the problem? During this time, I'll take a look at which steps are required to switch to the `symbol`endpint.

**Comment by dhung09** [comment]
@abe33 this is probably specific to local code. if you have this setup, you should be able to see this:

```python
# foo.py
def foo():
    pass
```

```python
# bar.py
from foo import *
```

Put your cursor over `foo` in `bar.py` and open the expand panel. Then if you click on the top member `foo`, you'll see the 404
