### ISSUE TITLE
Status text is missing in the status panel

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#238]
I was editing a python file. The status panel didn't display the usual text like "Kite is ready" at the bottom of the panel.
This might be related to #237 

![status-incomplete](https://user-images.githubusercontent.com/11473063/30108221-d0ccb2be-9301-11e7-9028-8a5866490e65.png)

**Comment by abe33** [comment]
What is the status of this file, is it whitelisted, blacklisted, something else?

**Comment by jansorg** [comment]
@abe33 There's a bug with whitelisting on windows, see https://github.com/kiteco/kiteco/issues/4805 . 
I think this issue might be caused by it. We should wait until that kite issue was resolved, I think.

**Comment by jansorg** [comment]
Fixed by change to kited.
