### ISSUE TITLE
"def" in hover popup opens file "untitled"

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#240]
Clicking on "def", shown in the screenshot below, opens a new file called "untitled".

![def-hover-popup](https://user-images.githubusercontent.com/11473063/30112604-414d99a8-9312-11e7-9e92-ed95f6b9d662.png)

**Comment by abe33** [comment]
I've got a fix for that, but it's still not ideal. Given we don't have a report along the signature response, I can't detect missing or empty definitions ahead of time and not display the link as we do in hover UI.

**Comment by jansorg** [comment]
@abe33 We might ask to get the callee's definition in the response. Would that be a better solution?

**Comment by abe33** [comment]
yep, that would  be a better solution

**Comment by jansorg** [comment]
@abe33 The feature request is at https://github.com/kiteco/kiteco/issues/4823 . This issue can wait until we some some feedback on the new request.
