### ISSUE TITLE
Get free Pro! appears after Kite pro is up and running.

### ISSUE THREAD

**Issue by hugeme** [kiteco/atom-plugin#244]
`Get free Pro!` message still appears after Kite pro is used. Restarting did not change that. However, the functionality corresponds to the pro version also all account setting.

[
<img width="235" alt="pro" src="https://user-images.githubusercontent.com/18237090/30340840-220b1b7e-97f4-11e7-9e19-eb95334ae888.png">
](url)

**Comment by abe33** [comment]
Hi @hugeme, thanks for taking the time to file a report. You're right, there's an issue here, I'll see with our designer how to fix that.

**Comment by liquidlotus** [comment]
I also have this issue except I am also being prompted to verify my email address, which I have already done.

<img width="293" alt="screen shot 2017-10-19 at 9 53 48 am" src="https://user-images.githubusercontent.com/3455435/31783549-791ba100-b4b3-11e7-8ab9-72c0c48e5f42.png">

**Comment by hugeme** [comment]
@jansorg  nope, thx!

**Comment by komskisp** [comment]
Kite asking to sign up for pro and stops displaying auto completions
