### ISSUE TITLE
Kite is running but not reachable!

### ISSUE THREAD

**Issue by hugeme** [kiteco/atom-plugin#246]
`Hydrogen: 1.22.0`
`ATOM: 1.20`
`MAC 10.12.5`

Hi,

I cant use my new plan on Kite anymore. I would appreciate any insight on how to change that again.

Launching Kite everything seems as always:

<img width="292" alt="first" src="https://user-images.githubusercontent.com/18237090/30511328-a3eb23ca-9ad6-11e7-9dff-5ecbf6dbbec0.png">

When executing the first code:

<img width="471" alt="second" src="https://user-images.githubusercontent.com/18237090/30511330-bfcd2746-9ad6-11e7-9e93-e38c5c28fdc6.png">

<img width="213" alt="third" src="https://user-images.githubusercontent.com/18237090/30511335-d2fade9e-9ad6-11e7-8d2d-d803bf1ef271.png">

**Comment by abe33** [comment]
Hi @hugeme, are you able to open `http://localhost:46624/settings` in your browser? Also, do you consistently get that message after manually restarting the kite process?

**Comment by hugeme** [comment]
Hi @abe33 , yes `http://localhost:46624/settings` works fine. Yes, I have followed the instructions by killing the corresponding process. Restart Kite. Restart atom. Remove atom cache in `~/.atom/storage`. Restart computer. Yes, I get this message consistently. However, it has worked fine, after changing from Kite basic to Kite pro for two days.

**Comment by abe33** [comment]
That's definitely weird, we're checking Kite reachability by making a `GET` request to `http://localhost:46624/settings` and as long as it responds something (even a `500` error) we're considering it as reachable. Kite being unreachable generally means that its server isn't running, and in that case the request fails with no status/response at all. 

If you have the latest version of the plugin you should be able to see the requests to `http://localhost:46624/settings` in the network panel of Atom's devtools. Do you mind taking a look at it and send me a screenshot of the various information there? There might be some clues as to what don't work here.

**Comment by akash1205** [comment]
@abe33  I am facing the same issue with Kite since yesterday.

**Comment by hugeme** [comment]
@abe33 could you pls give me a hint on how to use/open the network panel of Atom's devtools, it would be helpfull finding it at the first plance. then I can share with you that information

**Comment by abe33** [comment]
Oh, sorry, I forget sometime that everybody isn't web developer. So, in Atom on OSX (& chrome/chromium or firefox), you can open the devtools with <kbd>cmd+alt+i</kbd>, then you'll see a [Network](https://developer.chrome.com/devtools#improving-network-performance) tab where you'll see all the requests made by Atom. By using a [XHR filter](https://developers.google.com/web/tools/chrome-devtools/network-performance/resource-loading?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3#filter_requests) in that view, you'll be able to narrow down to only XHR requests (aka AJAX), Kite's requests will be there.

**Comment by hugeme** [comment]
<img width="111" alt="test" src="https://user-images.githubusercontent.com/18237090/30741682-1aa777fc-9f96-11e7-84a1-4b2306558926.png">
what particular information do I have to provide?

**Comment by hugeme** [comment]
perhaps its password related? clearing cache and restarting atom I have to log into:

<img width="524" alt="step1" src="https://user-images.githubusercontent.com/18237090/30742171-3aec6908-9f98-11e7-9741-8a94ca4d85bf.png">

After that I starting Kite :

<img width="538" alt="step2" src="https://user-images.githubusercontent.com/18237090/30742178-42d5c970-9f98-11e7-9843-ab9803fd5dce.png">

and put credentials:

<img width="584" alt="step3" src="https://user-images.githubusercontent.com/18237090/30742213-680fa576-9f98-11e7-996b-207c0348fd80.png">

which always returns invalid credentials. `{"code":6,"message":"incorrect password"}`


The credentials by intself are valid. I can Login and Logout offline and change settings. I also tried to reset the password :


<img width="1308" alt="password_reuqest" src="https://user-images.githubusercontent.com/18237090/30742426-39ab0670-9f99-11e7-84ea-b6a03e7577d1.png">

that doesnt work either. Something is strange here like the sync between my plan an the app

**Comment by abe33** [comment]
Hi @hugeme, thanks for taking the time of investigating the issue on your side, it definitely looks like some login issue, did you try to reset your password?

**Comment by hugeme** [comment]
HI @abe33, yes there is sceenshot on the top of your question of that result, requesting a new password.

**Comment by abe33** [comment]
Hi @hugeme sorry for the late reply, would you mind contacting us at [feedback@kite.com](mailto:feedback@kite.com) I think the issue is not solely related to the Atom plugin and someone will be able to help you with your log in issue.

**Comment by hugeme** [comment]
Hi @abe33, I will write am email to  feedback@kite.com. Not sure however what you mean with log in issue. I dont have any issue to login to kite. I just cant login to kite using atom plugin.

**Comment by abe33** [comment]
@hugeme Really I think I went to quickly through your reply and though you were not able to login into kite whatever the way. I could reproduce the password issue you encountered, investigating it right now.
