### ISSUE TITLE
Kite doesn't auto-complete the arguments name when calling a function

### ISSUE THREAD

**Issue by Frozenicev587** [kiteco/atom-plugin#264]
Hi, I was using kite for atom python programing, but after a upgrade, the auto-complete function doesn't work while I was writing arguments for a certain calling function. Such as:

....
add(apple_number, pear_number)
...

it doesn't auto-complete the variable 'apple_number' for me anymore even it's pre-defined. But it does auto-complete the function name 'add' if I just type like 'ad'.
Thanks for any help.

**Comment by abe33** [comment]
Hi @Frozenicev587, thank you for the report, I've found the source of this issue and have a fix ready, the patch should be available soon.
