### ISSUE TITLE
Use /docs/ instead of /docs/python/

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#269]
The webapp on kite.com supports the language-agnostic endpoint for docs now. Please make sure that the plugin uses `/docs/ID` instead of `/docs/python/ID`.

For example, the complete URL for Python's `json.dumps` is then:
http://localhost:46624/clientapi/desktoplogin?d=/docs/python;json.dumps

**Comment by abe33** [comment]
I forgot to link to that issue in my commit but this is now fixed on master and ready to be released

**Comment by jansorg** [comment]
@abe33 Thank you, I tested this successfully on windows with the latest update.
