### ISSUE TITLE
DeprecationWarning calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by ghstridr** [kiteco/atom-plugin#270]
Getting a stack trace when I switch away from the tab in Atom 1.21.1.
(node:47820) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
process.on @ internal/process/warning.js:21
emitOne @ events.js:96
emit @ events.js:188
process.nextTick @ internal/process/warning.js:47
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
/Users/michael.gracy/.atom/packages/kite/lib/kite.js:399 Uncaught (in promise) undefined
checkTextEditor @ /Users/michael.gracy/.atom/packages/kite/lib/kite.js:399
pollingInterval.setInterval @ /Users/michael.gracy/.atom/packages/kite/lib/kite.js:306

kite - 0.50.0
atom - 1.21.1
osx - 10.12.6

Atom plugins:
Community Packages (60) /Users/michael.gracy/.atom/packages
├── Sublime-Style-Column-Selection@1.7.4
├── atom-beautify@0.30.5
├── atom-ide-ui@0.5.3
├── atom-package-sync@0.2.6
├── atom-shell-commands@1.5.0
├── atom-typescript@11.0.10
├── autocomplete-ansible@0.1.15
├── autocomplete-bash-builtins@0.3.5
├── autocomplete-json@5.5.0 (disabled)
├── autocomplete-python@1.10.3
├── busy-signal@1.4.3
├── dash@1.7.1
├── file-icons@2.1.13
├── file-types@0.5.5
├── fold-lines@0.2.2
├── git-diff-details@1.4.0
├── git-plus@7.10.0
├── git-time-machine@1.5.9
├── go-debug@1.5.2 (disabled)
├── go-plus@5.6.0 (disabled)
├── go-signature-statusbar@1.2.3 (disabled)
├── gotests@0.3.0 (disabled)
├── hyperclick@0.1.5 (disabled)
├── ide-go@0.4.0 (disabled)
├── ide-json@0.1.0
├── ide-python@0.2.2
├── intentions@1.1.5
├── json-colorer@1.0.0
├── json-generator@0.1.15
├── jsonlint@1.1.4
├── kite@0.50.0
├── language-ansible@0.2.1
├── language-markdown@0.25.1
├── language-puppet@0.23.0
├── linter@2.2.0 (disabled)
├── linter-ansible-linting@1.3.0
├── linter-puppet-lint@0.8.3 (disabled)
├── linter-python@3.1.2
├── linter-python-pep8@0.2.0
├── linter-shellcheck@1.4.6
├── linter-ui-default@1.6.10
├── lipsum@0.1.0
├── markdown-pdf@2.1.0
├── markdown-preview-plus@2.4.16 (disabled)
├── markdown-scroll-sync@2.1.2
├── markdown-writer@2.7.3
├── overlay-status-icons@0.1.6
├── platformio-ide-terminal@2.7.0
├── project-manager@3.3.5
├── python-debugger@0.2.0
├── python-indent@1.1.2
├── python-nosetests@0.2.0
├── python-tools@0.6.9
├── qolor@0.4.2
├── save-session@0.15.7
├── ssh-config@0.12.0
├── svn@0.0.13
├── tool-bar@1.1.0
├── tool-bar-atom@1.7.0
└── zentabs@0.8.8

I can connect to localhost:46624:/settings. Kite engine is running.

**Comment by jansorg** [comment]
@ghstridr Sorry for this late reply!
Do you still get this with the current version of the plugin?

**Comment by ghstridr** [comment]
Sorry to say, but I uninstalled the plugin. So no, I'm no longer having the
problem.
