### ISSUE TITLE
"Install Kite" doesn't seem to work

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#273]
Testing on Windows 10

I uninstalled Kite and tried the "Install Kite" action. After a few minutes it still displayed the progress information, as shown in this screenshot:
![screenshot_20171030_112515](https://user-images.githubusercontent.com/11473063/32166045-02d01188-bd65-11e7-9b63-e3ef4f295f3d.png)

(I didn't see a popup by a setup program)

**Comment by simonacampo** [comment]
I have the same problem. It keeps telling me "Kite is installing"

**Comment by jansorg** [comment]
I debugged this a bit and noticed that `kite-app.js` calls the download with
```return StateController.downloadKite({
      onDownload: () => this.emitter.emit('did-download'),
      onInstallStart: () => this.emitter.emit('will-install'),
    })```
but the signature of the downloadKite function is `downloadKite(url, opts)`.

There seems to be a mixup of the passed arguments. `url` is omitted by the caller and therefore receives the value of `opts` as url.  The result is that `this.streamKiteDownload(url, opts.onDownloadProgress)` is called with a non-string url which then triggers that “connection refused to localhost:443” issue, I think (edited)
