### ISSUE TITLE
Status panel takes a long time to display if Kite isn't running

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#274]
- stop kite
- click on the status icon
- it takes a few seconds until the panel finally appears. See the request log in the screenshot
![screenshot_20171030_112515](https://user-images.githubusercontent.com/11473063/32166437-241df2f0-bd66-11e7-822c-03aa1663b26a.png)

(On my system requests take a a long time if the host/port isn't reachable. I had to limit the connection/request timeout for PyCharm to make this work properly on Windows.)

**Comment by abe33** [comment]
I don't think there's anything we can do. The `timeout` setting of a `XMLHttpRequest` (what we're using to contact `kited`) is here mostly for the request, so after the connection to the server was established. I couldn't find any documentation/topics about a connection timeout that would operate on the first handshake. But I did find topics where users were complaining that a lot of timeouts was not configurable in chrome, as we're using electron, which is based on chrome, this is not a good sign.

**Comment by jansorg** [comment]
@abe33 Thanks for the feedback. I'm closing this now as we can't solve this with what's available in Chrome/Electron.
