### ISSUE TITLE
autocomplete won't complete

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#276]
There seems to be some cases where hitting enter to complete a completion is a no-op: https://giphy.com/gifs/26uXN9fr9tPE5No6A/fullscreen

**Comment by abe33** [comment]
Hey @dhung09, can you confirm that you're using the `enter` or `tab and enter` options as suggestion confirmation in `autocomplete-plus`? Normally, once we have sent the suggestions to `autocomplete-plus` we no longer handle anything, it's the completion plugin that makes the insertion.

<img width="768" alt="settings_ ___development_javascript_kite-installer" src="https://user-images.githubusercontent.com/247140/32321511-a5e11f30-bfc1-11e7-9dbd-bae7260a1829.png">

**Comment by jansorg** [comment]
ping @dhung09 
Please close this if it's not relevant anymore.

**Comment by dhung09** [comment]
haven't seen this in a while, so assuming it's no longer a problem
