### ISSUE TITLE
Installation of Kite fails during/after download

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#282]
Plugin 0.55

1. I uninstalled Kite
2. I clicked the status icon and chose "Install kite" in the status panel
3. I waited for about 10 minutes
4. The panel which displays "Installing Kite..." was still visible after this time (See screenshot 1)
5. Kite wasn't installed in Windows after that
6. Nothing happens if I click on the status bar icon again after closing the status panel, i.e. the status panel won't appear again! (screenshot 2)

![install1](https://user-images.githubusercontent.com/11473063/33007029-1aace326-cdcd-11e7-99d0-a8ca309c9bac.png)
![install-2nd](https://user-images.githubusercontent.com/11473063/33007030-1d3d34f6-cdcd-11e7-9a44-8f09f03b291f.png)

**Comment by abe33** [comment]
@jansorg That should now be fixed on master. lmk if you see another issue.
