### ISSUE TITLE
failure to install kite

### ISSUE THREAD

**Issue by LuisAlarcon** [kiteco/atom-plugin#286]
output:

> npm WARN deprecated rollbar-browser@1.9.3: This package has been combined/moved to the package 'rollbar'
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\laala\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\laala\\AppData\\Local\\atom\\app-1.23.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\laala\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\laala\\.atom\\.apmrc" "install" "C:\\Users\\laala\\AppData\\Local\\Temp\\d-11802-14632-do6uf6.i02hp8pvi\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file C:\Users\laala\.atom\.apm\analytics-node\3.2.0\package\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\laala\.atom\.apm\analytics-node\3.2.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by abe33** [comment]
Hi @LuisAlarcon, it looks like some corrupted file when downloading the dependencies, can you retry to install the plugin again? Generally this is enough to fix this kind of install issue.

**Comment by LuisAlarcon** [comment]
Dear abe33,

I have done that and it is not working. I have even re-installed atom and tried to install the plug in again. However this has not been successful.

**Comment by jansorg** [comment]
@abe33 Do you have an idea how to further debug this?

**Comment by jansorg** [comment]
@LuisAlarcon This shouldn't be happening and we're not seeing this on our end.
Let us know if this is still an issue for you.
