### ISSUE TITLE
Rendering of instance with multiple types

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#293]
Rendering `b` in the expand panel renders the function `json.dumps` but should render instance information.

```python
b = 1 or 1.0 or json.dumps or None
```

**Comment by abe33** [comment]
Not sure to see the issue here. Here's what I get with that example: 
<img width="400" alt="sample_py_ ___github_kite_et_4__cedric_macbook-pro____development_gsoi_ufo-mobileapp__zsh_" src="https://user-images.githubusercontent.com/247140/35690906-681b02f8-0777-11e8-9503-ce5f0d15a97a.png">

**Comment by jansorg** [comment]
Hm, maybe this was fixed on the backend. Thanks for updating!
