### ISSUE TITLE
Cant use popular pattern while kite indexing code

### ISSUE THREAD

**Issue by hugeme** [kiteco/atom-plugin#297]
Hydrogen: 2.2.2
ATOM: 1.23.3
MAC 10.12.5

Hi, Im having some trouble using the popular pattern feature. It seems that it  is not show as long as kite is indexing code. However, kite doesnt stop indexing code. That phenomenon last for almost one month. Do not know what to do. Appreciate any insights! 
<img width="230" alt="poppattern" src="https://user-images.githubusercontent.com/18237090/35354499-71ccc68e-014a-11e8-9d0e-e586c1e2f00d.png">

**Comment by jansorg** [comment]
@hugeme Sorry for the late reply!
There are two issues here: kited doesn't stop indexing and popular patterns not working.

Kited supports popular patterns for SDK/global library calls during indexing. Calls of your own functions won't work during indexing.
Could you add a snippet where the patterns aren't working for you?

The other issue is that kited isn't stopping to index. Is this still happening for you?

These details will help us to look into this:
- which version of Kite are you using?
- which platform are you on (Mac / Windows)?
- a rough estimate of the number of whitelisted files (e.g. hundreds, thousands, ...)

**Comment by jansorg** [comment]
@hugeme Feel free to reopen with the details requested above.
