### ISSUE TITLE
Dedupe completions

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#298]
If possible, we should remove duplicate completions in order to take up less screen space:

![image](https://user-images.githubusercontent.com/3752225/35600697-1e8b31ce-05e4-11e8-8468-4f7dacbd5c57.png)

If this is not possible in Atom, feel free to close this issue

**Comment by jansorg** [comment]
This is not possible in Atom, therefore we're closing this. You can't access completions returned by other providers.

**Comment by adamsmith** [comment]
Maybe we could file an issue, and/or submit a patch to [autocomplete-plus](https://github.com/atom/autocomplete-plus) to do this?

A couple of options for how to choose which result "wins" when there are dupes:

* The entry with the most info "win", e.g. in terms of documentation, etc.
* Providers could return a "priority", e.g. as with the ranking of completions.

It seems like this would be a big improvement for autocomplete-plus.

(The priority here should be low-ish, though?)

**Comment by abe33** [comment]
Ok, I've missed that at the time, but they added a setting to let the user turn it off -> https://github.com/atom/autocomplete-plus/pull/893
![settings_ ___github_kite](https://user-images.githubusercontent.com/247140/37357079-c463d794-26e7-11e8-9a1b-a38276353665.png)

**Comment by adamsmith** [comment]
Hm, interesting.  There seems to be a `excludeLowerPriority` option.  If we set that to `true` would that "override" the referenced setting?

If not, it seems to me like they chose the wrong solution here.  Not deduping results _from different providers_ by default seems like a mistake, e.g. as in https://github.com/atom/autocomplete-plus/issues/913.
