### ISSUE TITLE
On Kite update: "You need to login to the Kite engine"

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#305]
(Possibly related to https://github.com/kiteco/vscode-plugin/issues/87)

When my Kite installation updated today I got the logged out notification.

![screen shot 2018-02-08 at 5 38 02 pm](https://user-images.githubusercontent.com/87728/36008375-e5540222-0cfb-11e8-84f4-434d350b9332.png)

**Comment by abe33** [comment]
Hmm, but how can I know in which case we're in? 
I mean if we get this message it's that during the update our polling routine passed at a point where the authorized endpoint didn't respond but the new kite was still installed and running (same with vscode actually, the routine might have passed while the install could no longer be found on the system). What's the difference between a legit uninstall/unlogged state and a false positive during an update? We really need to devise a strategy to let all plugins kwow when a update is in progress.
