### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#306]
I’m probably reading this incorrectly but it seems like as we send events in `EditorEvents.mergeEvents()` we don’t delete them from `pendingEvents`.  I’m wondering if this could be the cause of a memory leak?

Also, it may not be enough to delete events we send in `mergeEvents()` because we call `clearTimeout()` so there’s not a one to one ratio between adding events to `pendingEvents` and calls to `mergeEvents()`.

**Comment by abe33** [comment]
Nice catch, I'm not sure why we ended up not clearing the array once merged, maybe just an omission. I'll push a patch asap.
