### ISSUE TITLE
Yellow Kite icon because of dir whitelisting should only appear for .py files

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#31]
We probably shouldn't draw attention to the Kite icon if the user is in an unsaved file, or a non-.py file.

**Comment by abe33** [comment]
On that front, I think that we shouldn't notify the user about whitelisting unless he opens a python file. Actually it's triggered for every files. What do you think?

**Comment by alexflint** [comment]
@abe33 agreed - should not show anything unless the user is in a file that has been saved with a .py extension

**Comment by abe33** [comment]
Then I would probably suggest something like this for the status icon: 
- Kite not installed, not started or not reachable : red icon
- Kite not authenticated: yellow icon
- Kite authenticated, but directory not whitelisted, and no python file open: blue icon (telling that Kite is ready but not active)
- Kite authenticated, directory not whitelisted, and a python file open: yellow icon (calling to action)
- Within a whitelisted directory, and no python file open: blue icon (still in our ready but not active state)
- Within a whitelisted directory, and a python file open: green icon (kite is ready and active for this file).

And for the notifications, as long as we're still in the blue state we never display notifications, the only case will be when a user open a python file from a non-whitelisted directory.

**Comment by adamsmith** [comment]
This looks great, thank you for breaking it down!

My only suggestion would be to replace green with blue, so there are fewer states (basically blue=thumbs up, yellow=something needs attention, red=oh damn).
