### ISSUE TITLE
every time asking to install

### ISSUE THREAD

**Issue by shekharsumans** [kiteco/atom-plugin#310]
every time i open atom it is showing kite is ready 
but again it is asking to install

**Comment by abe33** [comment]
Hello @shekharsumans, sorry to hear about that, can you tell us a bit more about your config? Such as: 
- which version of Atom are you running
- which version of Kite's atom plugin is installed
- which version of Kite is installed
- what are your OS?

**Comment by adamsmith** [comment]
Also, @shekharsumans it may be helpful to see a screenshot of the text that's asking you to install, if it's reproducible.  Thanks!

**Comment by jansorg** [comment]
@shekharsumans Do you have an update on this? :)

**Comment by adamsmith** [comment]
@jansorg should we close this?

**Comment by jansorg** [comment]
@shekharsumans Pleae re-open if this is still happening for you
