### ISSUE TITLE
Atom Kite Startup Time

### ISSUE THREAD

**Issue by arv1362** [kiteco/atom-plugin#319]
The startup time of kite is increasing as time goes on which slows my coding time till i have to disable the package

![capture](https://user-images.githubusercontent.com/33993859/36541205-21a283f8-1818-11e8-8e31-34cae0c2e2bb.PNG)

**Comment by abe33** [comment]
Hello @arv1362,

Could you tell us a few things regarding your config?

- What is your OS?
- What is your Atom version?
- Do you see the same long startup time when the kite process is not running than when it is running?
- Do you see the same long startup time when starting Atom with no project?
- Do you see the same long startup time when starting Atom in a new directory?

**Comment by arv1362** [comment]
-Windows 7 Ultimate
- Version 1.24.0
-The startup time is slightly shorter (3440ms) when the kite is not running
-No, the startup time will be very short
-Yes

**Comment by arv1362** [comment]
Windows 7 Ultimate

Version 1.24.0
-The startup time is slightly shorter (3440ms) when the kite is not running
-No, the startup time will be very short
-Yes

**Comment by arv1362** [comment]
Windows 7 Ultimate

Version 1.24.0
-The startup time is slightly shorter (3440ms) when the kite is not running
-No, the startup time will be very short
-Yes

**Comment by abe33** [comment]
Thanks @arv1362, that helps a lot! I might have figured a way to speed up the package startup time and I'll see with the other developers in charge of the kite process how to handle this.

**Comment by abe33** [comment]
Maybe a last question. 

Do you see a difference in startup time when there are files open in a project VS when no files are open?

**Comment by arv1362** [comment]
It doesn't show any significant difference even when no files are open

**Comment by abe33** [comment]
Hey @arv1362, we've released a version that should have improved things, can you confirm it or do you still see this high activation time?

**Comment by jansorg** [comment]
@arv1362 If the newest version is still too slow at startup, then let us know, please.
