### ISSUE TITLE
Autocomplete pop-up shouldn’t show “def” for built-in functions?

### ISSUE THREAD

**Issue by mwichary** [kiteco/atom-plugin#322]
Example:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/2061609/36699268-ff49caaa-1b00-11e8-8683-b34b4847042e.png">

As far as I understand, “def” should be there only for own functions, rather than built-in ones.

Clicking on “def” shows this:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/2061609/36699310-18627e2e-1b01-11e8-8df3-6ea222e662cf.png">

**Comment by abe33** [comment]
The issue is quite the same than with the signature panel, as we don't have any clue as whether the entry has a definition or not (we've only access to its id). The solution is probably to just get rid of it like in the signature panel (until we devise a new strategy).

**Comment by mwichary** [comment]
Interesting, thanks! Your solution sounds great. Would it be possible – in the fullness of time – to add this bit of information here alongside the id?
