### ISSUE TITLE
Add pane in View menu?

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#342]
@mwichary @abe33 
This is related to #337 which implement a native sidebar pane.

We could add "Toggle Kite pane" if that makes sense.
Do plugins usually add the pane in the view menu? 

Feel free to close this if not making sense or if we shouldn't do this.

![screenshot_20180315_113841](https://user-images.githubusercontent.com/11473063/37458459-69ff4be4-2845-11e8-823c-4dbacedf944c.png)

**Comment by mwichary** [comment]
I like this a lot. I didn’t even know this was possible.

One thing to remember: We’ll have two panes soon (regular + autocorrect). How would that work? I am assuming we’d hide both if you toggle it away, and show whatever was the last state if you toggle it back in. Is that possible?

The label should probably be `Toogle Kite Tab` or `Tabs` for consistency?

**Comment by abe33** [comment]
I don't think we should have one command for both. As you can see, github has two commands for the `Git` tab (commit, diff, etc.) and the `Github` tab (PR stuff). Same thing for us, each of our panes are specific entities with specific commands, it doesn't make sense to have these merged into one.
As for adding these commands to the menu, it's just a matter of putting the corresponding entries in https://github.com/kiteco/atom-plugin/blob/master/menus/kite.cson (the github one for reference: https://github.com/atom/github/blob/master/menus/git.cson)
