### ISSUE TITLE
Not able to enable kite

### ISSUE THREAD

**Issue by derek-schultz** [kiteco/atom-plugin#35]
```
The Kite autocomplete engine is disabled for <file>

Would you like to enable Kite for Python files in <path>?
```
(filename and path redacted)

If I press Enable, the same popup reappears indefinitely. It goes away until the next time I re-enable Kite.

Enabling via the actual Kite app works fine for the same directory.

**Comment by adamsmith** [comment]
This should be fixed now.  Please reopen if you're still encountering it.  Thanks!
