### ISSUE TITLE
Standardize commands

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#387]
Refer to [this doc](https://kite.quip.com/HinNAHAoaVpH/Kite-commands-in-editors) to see the in-depth discussion of these commands.

To summarize, these commands (and only these commands) should be implemented:

- [x] Kite: Docs at cursor
- [x] Kite: Open sidebar
- [x] Kite: Close sidebar
- [x] Kite: Open Error Rescue sidebar
- [x] Kite: Close Error Rescue sidebar
- [x] Kite: Open Copilot
- [x] Kite: Search
- [x] Kite: General settings
- [x] Kite: Permissions
- [x] Kite: Editor plugin settings
- [x] Kite: Status
- [x] Kite: Help
  - This should link to https://help.kite.com/category/43-atom-integration

**Comment by abe33** [comment]
Closing this now, given the PR have been merged
