### ISSUE TITLE
Add padding to user defined docs

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#393]
For user defined docstrings, we should add some padding between the content and its container:

![image](https://user-images.githubusercontent.com/3752225/39325522-468f0a5a-4947-11e8-89ff-c92b80e54cdb.png)

**Comment by mwichary** [comment]
Related: https://github.com/kiteco/kiteco/issues/5578

**Comment by dhung09** [comment]
not a high priority atm
