### ISSUE TITLE
Developer mode styling

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#405]
Copying over [comment from previous PR](https://github.com/kiteco/atom-plugin/pull/382#issuecomment-384049358)

> FYI some of the styling is strange when developer mode is turned on (I use this sometimes for quick debugging), but I think that can be addressed in another PR. Just adding some screenshots here

> Box around the kind of the value is stretched out:
![image](https://user-images.githubusercontent.com/3752225/39209091-b3d51620-47b9-11e8-87f6-7d7dd2b61730.png)

> We could probably change the background color in the sidebar to make it more clear that it's debug output:
![image](https://user-images.githubusercontent.com/3752225/39209684-499191f6-47bb-11e8-9a48-60d1ede95ed4.png)

**Comment by abe33** [comment]
It looks like the first issue have been corrected in the meantime. In your screenshot it seems the label doesn't have its `flex` property define and as such the width is divided between the two elements. In the current version we have a `flex: 1 1 0` which mean that the label is going to grow/shrink depending on the available space. Also, in your screenshot it seems the hover panel is lacking the `max-width: 20em` it has on master. 
![sample_py_ ___github_kite](https://user-images.githubusercontent.com/247140/39807211-02c3477a-537c-11e8-8ef1-b5d4a7336e37.png)

For the second point I have a PR ready.
