### ISSUE TITLE
Function call parameter not highlighted correctly

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#406]
__On v0.86.0__

To reproduce:

```python
import json
json.dumps({}, sort_keys= # cursor here
```

The signature UI shows `skipkeys` as the current argument. The expected outcome is to see `sort_keys` highlighted. This seems to be an Atom specific issue because testing on other editors worked fine.

**Comment by abe33** [comment]
Apparently, this is a side effect of the memoization introduced by @dbratz1177 to make it more consistent with VSCode (vscode signature providers are only called after a `(` or a `,`). Removing the memoization fixes that issue. 

@dhung09 @dbratz1177 : What's your thought on that, shall I just get rid of that caching and make a request on each keystroke instead?

**Comment by dhung09** [comment]
I think it's fine to not use caching for now. VS Code behavior may be too restrictive for what we may want to do in the future also.
