### ISSUE TITLE
Irregular behavior of new editor panels

### ISSUE THREAD

**Issue by keien** [kiteco/atom-plugin#41]
sorry the title isn't more descriptive, don't really know the specific nature of the problem so just refer to the GIF:
![feb-02-2017 14-08-34](https://cloud.githubusercontent.com/assets/1103512/22570645/2509fc3e-e951-11e6-8365-61f5b799623d.gif)
In this capture, I'm hitting return after the full `requests` completion comes up.

**Comment by keien** [comment]
cc @adamsmith

**Comment by abe33** [comment]
Right, autocomplete-plus is selecting the word before replacing it, and in that case the word matches a hover token so we end up displaying the expand view. 

The more I think about that the more I feel we should not display the expand view using a selection. There's too much scenarios that lead to having a word selected (Antonio also reported that cycling through find-and-replace results was triggering the expand view). I think we should fallback to using only a command (with a keybinding) and a button in the hover view (as done with the sidebar version in my sidebar UI branch).

**Comment by adamsmith** [comment]
cc @alexflint for any input

It sounds like autocomplete-plus implemented a hack, and that we need to hack around their hack to me isn't a sign that there's something fundamentally wrong with our approach.

It will take some engineering to get this to work, and we won't have 100% precision and recall, but we should be able to get close, and I still believe it will be worthwhile in the end.

**Comment by jlozano** [comment]
@abe33 can we close this?
