### ISSUE TITLE
Permissions in status panel not disabled when Kite isn't running

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#430]
I've noticed this in branch cn-replace-kite-installer-use. I didn't check if this is in master, too.
Clicking "Permissions" opens a link in the web browser, Kite isn't running though. It should be disabled.

![bildschirmfoto 2018-06-05 um 14 52 46](https://user-images.githubusercontent.com/11473063/40977086-40c28b3a-68d0-11e8-8166-75ec76ec5ce9.png)

**Comment by abe33** [comment]
Right, this is also happening on master, the link lack a `account-dependent` class to make it behaves just like the `Kite Settings` action above.
