### ISSUE TITLE
Popular patterns flash when writing a string as an argument

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#435]
In the GIF below, the experience is totally smooth for all cases, other than when I type `'` to start a string.  When this happens, there's a dramatic flicker where the panel goes away and then comes back.

![jun-08-2018 13-22-52](https://user-images.githubusercontent.com/87728/41179376-553b097e-6b1f-11e8-89e2-86d22753362f.gif)

**Comment by abe33** [comment]
I don't seem to reproduce

Here's without `bracket-matcher` completing the quote and parenthesis: 
![Uploading kite-flicker-no-bracket-completion.gif…]()

Here's with `bracket-matcher` completing the quote and parenthesis: 
![kite-flicker](https://user-images.githubusercontent.com/247140/41222003-22a4f4ae-6d66-11e8-9e10-1ae0e6763c2d.gif)

**Comment by adamsmith** [comment]
After updating from Atom 1.26.1 to 1.27.2, this is resolved.

Cedric: "I just want to make sure it was something known and fixed in autocomplete-plus and not some side-effect of a change, otherwise we can’t be sure it won’t come back later"

**Comment by abe33** [comment]
So far I haven't found any traces of a recent issue regarding that flicker, so it's likely a side effect of another change (either in autocomplete-plus or in another part of Atom). I'll continue to investigate a bit.

**Comment by jansorg** [comment]
Closing for now.
