### ISSUE TITLE
read-arch.bat won't work for international Windows

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#44]
Unfortunately "Program Files (x86)" has a different name on different Windows languages.  I found the following snippet on StackOverflow which seems to work across Win 7-10.

```
@echo OFF
setlocal EnableDelayedExpansion

reg Query "HKLM\Hardware\Description\System\CentralProcessor\0" | find /i "x86" > NUL && set OS=32BIT || set OS=64BIT

if %OS%==32BIT echo 32bit
if %OS%==64BIT echo 64bit
```

**Comment by abe33** [comment]
Are you sure? I'm on a french windows and it's named "Program Files (x86)". Anyway, I'll use that snippet to avoid any issue.
