### ISSUE TITLE
completions pane doesn't go away on Enter

### ISSUE THREAD

**Issue by metalogical** [kiteco/atom-plugin#448]
which prevents me from inserting a newline without moving my cursor first
![no_enter](https://user-images.githubusercontent.com/1977419/41931212-471a809c-7932-11e8-85a7-f3726f3440eb.gif)

**Comment by dbratz1177** [comment]
So what's happening mechanically:
- insertion of `x` triggers autocomplete suggestions, which is populated by our provider
- autocomplete suggestion of `x` replaces `x`
- the insertion of `x` triggers autocomplete suggestions
- ...
Oddly enough, this only happens for single character inserts, almost as if autocomplete-plus interprets single insertions that it makes to be equivalent to a keystroke generated insertion

**Comment by dbratz1177** [comment]
There seems to be a really nasty interaction between our Promise based responses in `getSuggestions` and `autocomplete-plus`'s handling of single-character-identical-text replacements.

The following cases could be instructive for an eventual solution:
- Note the difference if `getSuggestions` instead takes on the following forms:
![screen shot 2018-06-26 at 3 22 47 pm](https://user-images.githubusercontent.com/6146901/41942801-c9259432-7955-11e8-9a1e-f5f6c2f84bed.png)
vs.
![screen shot 2018-06-26 at 3 23 48 pm](https://user-images.githubusercontent.com/6146901/41942811-d09b6994-7955-11e8-83d7-981f8f69775b.png)
- toggling between the `x` suggestions yields the same basic behavior that triggered the filing of this issue:
<img width="379" alt="screen shot 2018-06-26 at 3 28 28 pm" src="https://user-images.githubusercontent.com/6146901/41942845-fad9b7ba-7955-11e8-9cc1-655f954f8ed0.png">

**Comment by abe33** [comment]
There's definitely something going on with the duration of a completions provider, 
A quick test in `init.coffee` (the default user startup script) gives us a hint at that: 

```coffee
# With no timeout, the provider won't show up a second time when confirming the insertion
atom.packages.serviceHub.provide 'autocomplete.provider', '2.0.0', {
    selector: '*'
    getSuggestions: -> Promise.resolve([{text: 'y'}])
  }

```

```coffee
# With the timeout it's now impossible to get the completion panel to not show up again on confirmation
atom.packages.serviceHub.provide 'autocomplete.provider', '2.0.0', {
    selector: '*'
    getSuggestions: ->
      new Promise((resolve, reject) ->
        setTimeout((-> resolve([{text: 'y'}])), 0))
  }
```

Now, removing that initial delay don't solve the issue, as we're still taking some time to return suggestions (there's possible a call to plan then signature then completions, which all take some time).

It looks like we have many options here: 
1. consider this is an issue in autocomplete-plus -> report it, maybe providing a patch if we can and feel this should be addressed asap
2. monkey patch that in the plugin, fixing it for our own suggestions, with the risk of the patch breaking with a future update
3. stripping one char entries from the provided suggestions

I guess 1 is probably the best long term solution, but it's also the one that will take the most time to reach end users (we need github to acknoledge the issue, and then we need to find a fix, write a test, submit a pr and hope github will merge it quickly). 
2 is clearly the best short term solution, we can probably track whether the change was induced by completions and prevents completions to be triggered again.

I'll try to go with 2 first then look quickly for 1 to see if it's worth the pain.

**Comment by abe33** [comment]
After some search I still have no clue as to why the completions don't show up in the case of a provider that returns a promise that resolves quickly vs one with a 0 timeout. I do have a patch using method 2, but I feel like using it to provide one won't really work.

**Comment by metalogical** [comment]
![gif](https://user-images.githubusercontent.com/1977419/54143603-686d2300-43e7-11e9-9d0b-d7c718bc03d0.gif)

this appears to have regressed for me, can you confirm? @abe33 

cc @dbratz1177

**Comment by jansorg** [comment]
I'm not sure if I'm best to fix this.
cc @dbratz1177

**Comment by dbratz1177** [comment]
I'll look into this this morning

**Comment by dbratz1177** [comment]
@metalogical I'm not able to reproduce this behavior off of `master`:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6146901/54296715-a8144600-4572-11e9-8e62-9b00139073ce.gif)

What version of atom / our plugin did you see this in?

**Comment by dbratz1177** [comment]
Weird - I'm getting this behavior when using the latest production version of the plugin...
