### ISSUE TITLE
Kite installation ask for administrator credentials

### ISSUE THREAD

**Issue by AJediIAm** [kiteco/atom-plugin#456]
I'm running atom as a local user without administrator privileges. When I tried to install Kite (via autocomplete-python), I was asked for administrator privileges which I cannot provide. When I declined the credentials an "undefined" error the error text "undefined" was given and Kite did not finish the installation. After restarting atom, Kite was still disabled. Repeating the process gave the same results. 

edit: In also tried to install kite via the command line. The kite package is shown in atom, but the same error is given when enabling kite in autocomplete-python.

**Comment by its-dhung** [comment]
Unfortunately you would need admin rights to install the Kite executable, so no fix on the horizon for this.

**Comment by Coderoftheworld** [comment]
What if we signed up on the website, then the .exe would already be prepared with our credentials and you could download the zip
