### ISSUE TITLE
Completions incorrectly trimming leading spaces

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#458]
To reproduce:
```python
import matplotlib.pyplot # cursor here
```
The completion `pyplot as plt` should be shown. When selected, the text becomes `pyplotas plt` instead of `pyplot as plt`. This doesn't seem to be an issue in other editors.

**Comment by jlozano** [comment]
@damiankite what does the `insert` field of the completion contain in this case?

**Comment by damiankite** [comment]
Should be `pyplot as plt`.

**Comment by dhung09** [comment]
this seems to work fine on my work computer actually. will close this now and check again on my home setup

**Comment by dhung09** [comment]
reopening this since it seems to still be an issue

![jul-20-2018 16-41-10](https://user-images.githubusercontent.com/3752225/43029513-c0396828-8c3b-11e8-97eb-345e7d2e66b6.gif)

atom v1.23.1
kite v0.99.0

**Comment by damiankite** [comment]
Ah whoops, I didn't notice the trailing space. In this case, the `Attr` field should be empty and the `Insert` field should be `as plt`.

FWIW, I can't duplicate this myself. Perhaps this is related to the Atom version or the kited/plugin version? I'm using  Atom 1.28.2 on Mac, with Kite from master.

**Comment by dhung09** [comment]
seems like my atom version is pretty behind then. if it's a regression caused by different versions of atom, then we could either patch it here or we could make it a policy that we don't only support atom v1.2X or above? @abe33 not sure what the right thing to do here is

**Comment by abe33** [comment]
I don't reproduce either on latest atom+kite, I've tried to see if there was a reason why it would eat some content while inserting a suggestion in 1.23 but I couldn't find anything (and apparently I'm no longer able to build 1.23 releases with my current setup).
But yeah, I think it's fair to start cutting support for old versions (fwiw 1.23 is from january this year)

**Comment by abe33** [comment]
After more research, there's this commit https://github.com/atom/autocomplete-plus/pull/930/commits/07fcb5696fa4cae8cc4961ac4896c116284e7468 introduced in 1.23.3 that change the rule to compute the prefix to replace when inserting a suggestion, that could explain why the ` ` would be eaten prior to this commit, but not why the `as` is eaten as in your last example.

**Comment by abe33** [comment]
I could confirm that on 1.23.0, and there's also a weird substitution in the display text, I see `pyplot_as plt`. I guess we can raise the requirement for Atom version.

**Comment by abe33** [comment]
Ok, anyway, I found a fix that works for all versions, pushing it soon
