### ISSUE TITLE
how to open the "sidebar" in the atom and "Docs following cursor" does not work

### ISSUE THREAD

**Issue by zhangsh950618** [kiteco/atom-plugin#468]
Hi, I am confused with the command "open-sidebar".![screen shot 2018-08-03 at 21 30 17](https://user-images.githubusercontent.com/39693134/43645431-72f0cbea-9764-11e8-8ba1-bd2a2b593a78.png)
I use the atom 1.29.0, but i can not find the command.
![screen shot 2018-08-03 at 21 29 25](https://user-images.githubusercontent.com/39693134/43645511-b4cf7502-9764-11e8-9ef9-919e88a3fc5d.png)
And the second problem is "Docs following cursor" does not work.

**Comment by zhangsh950618** [comment]
hi, thanks for you reply.
I am straight forward to the second bug, "Docs following cursor".
 The Atom version is 1.29, the kite version is 0.1.0, the mac version is
10.13.6 .

I spend nearly whole day to find the reason. After  restarting the mac ,  "Docs
following cursor" works.


Cédric Néhémie <notifications@github.com> 于2018年8月6日周一 下午3:30写道：

**Comment by zhangsh950618** [comment]
Excuse again，i am writing the code with Pytorch, but found few documents,I hope you can add more detail documents and examples in the kite,thanks

**Comment by abe33** [comment]
Thanks for the follow up and glad it works now, my guess is that Kite was still probably indexing your code, as for pytorch, I'll pass the word to the team as I'm not dealing with providing the documentation.
