### ISSUE TITLE
completion selection duplicates identifier

### ISSUE THREAD

**Issue by namanbharadwaj** [kiteco/atom-plugin#471]
![issue](https://user-images.githubusercontent.com/1977419/43729226-74f47712-995c-11e8-9dee-8b67c846e8ad.gif)

If you type out the full text `md5` and then hit enter (to select the `md5` completion), then the identifier gets duplicated. This appears to happen for identifiers ending in a numeric character.

**Comment by abe33** [comment]
@namanbharadwaj hmm that's interesting, what's your version of Atom? because on a build from their master branch I don't see this issue
![import-md5](https://user-images.githubusercontent.com/247140/43767541-b3286744-9a35-11e8-98ee-cbbaeab4f2d3.gif)

**Comment by namanbharadwaj** [comment]
I'm running 1.29.0. The issue occurs when typing `md5` in full, and *then* hitting enter (not sure if you're just typing `md` and hitting enter).

**Comment by abe33** [comment]
Thanks for the heads up, I could reproduce, fix is on its way
