### ISSUE TITLE
duplicate window on 'more'

### ISSUE THREAD

**Issue by dbratz1177** [kiteco/atom-plugin#472]
Surfaced in QA, in windows:
https://drive.google.com/file/d/1gLPpgSeqUgLQTnLBw0MmAFDRQ0JX8uBm/view

**Comment by abe33** [comment]
Isn't that more an issue with the electron app? From windows `cmd`, using `start kite://settings` I see the same thing (in VSCode as well, given it spawns `cmd` to run `start` as well)

**Comment by dbratz1177** [comment]
I'll close this and move it over there then
