### ISSUE TITLE
CPU usage 56% even when Atom is not launched

### ISSUE THREAD

**Issue by MPukelis** [kiteco/atom-plugin#477]

**Comment by jansorg** [comment]
@MPukelis Thanks for reporting this!

Which OS are you using?

Do you leave your machine running for a long time (i.e. suspending instead of shutting it down)?
Will this go away if you restart your machine? We've fixed CPU performance issues a few weeks ago. If it happened that Kite's automatic update wasn't performed on your machine then a restart could fix this.
Alternatively try to restart the Kite application / executable.

**Comment by MPukelis** [comment]
Hi, thank you for taking the time to respond. 

I am using windows 10 on a powerful dell xps 15 with i7 and 16gb ram. 
The atom package was only installed on the 16th of August. 
2 days after I noticed the fans spinning up and laptop getting really hot even when the laptop was not running. 

In the task manager a node server application was running using up to 60% of CPU resources.
I uninstalled node from my computer and the problem stayed.
I rebooted and ensured atom editor was no running. 
About 5 minutes later the laptop got hot again and the node.js server application was running again.
As soon as I launched Atom and uninstalled kite the problem resolved.

**Comment by jansorg** [comment]
HI @MPukelis ,
thank you for providing further details.

Do you remember what name was shown in the task manager for the node.js server application?
The Kite plugin doesn't start a separate node.js process. 
It starts the Kite application though. 

Do you observe the same performance issues when you quit Atom and start the Kite application? The Kite application should be available in your start menu applications.

**Comment by MPukelis** [comment]
C:\Users\Mantas\AppData\Local\atom\app-1.29.0\resources\app\apm\bin

I installed kite again and this starts up and uses up to 100%. This process does not seem to start without kite installed on my pc. Is this a Atom related bug?

![image](https://user-images.githubusercontent.com/18720878/44432664-e3313680-a59a-11e8-81b0-1ca2e76102c1.png)

**Comment by jansorg** [comment]
@MPukelis Thanks for the details.
Kite uses Atom's `apm` command to update version of the Kite plugin used by Atom. This should only check the version and update when necessary. Is Atom installed in a special way, e.g. with restricted restrictions?
Do you see this when updating plugins from within Atom?

There's a workaround to make Kite stop running that command:
Go to `C:\Users\Mantas\AppData\Local\Kite` and create a file called `PLUGIN_DEBUG`, the full path is `C:\Users\Mantas\AppData\Local\Kite\PLUGIN_DEBUG` (no extension). This makes Kite stop to update any plugin on your system, including Atom. You can still use the Copilot to update manually, of course. Using Atom to update the plugin is possible, too.

Does this workaround fix your issue?

**Comment by jansorg** [comment]
Closing, let us know if you need further help with this.
