### ISSUE TITLE
bring back definition link in completions panel

### ISSUE THREAD

**Issue by metalogical** [kiteco/atom-plugin#483]
It looks like it was removed here: https://github.com/kiteco/atom-plugin/pull/326

This causes the completions panel & hover panel to be inconsistent. I would propose bringing it back to the completions panel. What are the blockers for bringing it back?

cc @dhung09

**Comment by dhung09** [comment]
i don't think the definition is included in the completions response. the definition is only contained in the report response, which may be too heavy to return back with completions

**Comment by namanbharadwaj** [comment]
ah good point. The definition is actually only a filename + line number (no source string), but I guess it's up for debate whether it's worth returning with completions.
