### ISSUE TITLE
signatures request not made when matching close paren exists after cursor

### ISSUE THREAD

**Issue by namanbharadwaj** [kiteco/atom-plugin#484]
e.g. if I type

```
import json
json.dumps(|)
```

then the signature request is made and the panel pops up. However, after typing 

```
import json
json.dumps(x, |)
```

the signature panel does not reappear, and a request is not remade to kited.

On the other hand, if the closing paren does not exist (i.e. I manually delete it, since Atom creates the close paren automatically), the signature request is remade and the panel pops up.
```
import json
json.dumps(x, |
```

cc @dbratz1177

**Comment by abe33** [comment]
Thanks for the report, I have now a PR ready for this. 

Sadly these kind of errors are bound to appear again as we're relying on the language grammar in atom to define what is and what is not a function call and sadly this have proven to be quite unstable as they're frequently tweaking the scopes they're using for arguments.

**Comment by namanbharadwaj** [comment]
We could improve upon this by returning the AST state (e.g. "in call expression") as part of the event/completions response; that way all the parsing logic can be centralized in the backend / kited.

Not sure exactly what sort of API change would be most amenable to integration into the editor plugins, but we can discuss this separately.
