### ISSUE TITLE
Login to Kite not working

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#496]
Windows 10
Fresh user account

- Installed Atom
- Launched Atom and installed the Kite package
- (Installed Kite)
- Clicked on the statuc icon and then on "Login now"
- I entered my username and an invalid password
- I click on "Sign into Kite"
- Nothing happened, no error message or any other message was displayed. The login screen remained as it was before. I had to close it to continue.

![screenshot_20180925_171737](https://user-images.githubusercontent.com/11473063/46024362-eada8280-c0e6-11e8-997b-6741611fda77.png)

**Comment by abe33** [comment]
I can reproduce on OSX, so it's not specific to windows. 

Until now we were using `/api/account/login`, and it's now responding with a `200` (hence why no errors are displayed) but don't log us in Kite. OTOH `/clientapi/login` is giving me a `500 request Content-Type isn't multipart/form-data`, I don't recall kited endpoint using multipart/form-data (we were only using form data until now), is that a recent change or did I miss something?

**Comment by abe33** [comment]
Closing as we're now sending users to the copilot for login
