### ISSUE TITLE
Offer to turn off tree-sitter parsing on startup

### ISSUE THREAD

**Issue by dhung09** [kiteco/atom-plugin#514]
(See #512 for context)

On plugin startup, we should detect if the user is using the tree-sitter parser and offer to turn it off.

You can detect this setting via:
```javascript
atom.config.get('core.useTreeSitterParsers')
```

The notification to be shown should look like:
![image](https://user-images.githubusercontent.com/3752225/47757973-190f2d00-dc66-11e8-91df-aee0e1123572.png)

Code to generate the notification (we'll replace the link with another one):
```javascript
atom.notifications.addWarning('Kite is not configured properly', {
  description: 'You must turn off Atom\'s tree-sitter parser for Kite to show you information on how to call functions. <a href="https://kite.com">Learn more</a>',
  dismissable: true, 
  buttons: [{text: 'Turn off'}]
})
```

Clicking on the "Turn off" button should disable the tree-sitter setting.

This notification should be shown on _every_ startup because the tree-sitter setting takes away a signification portion of Kite's functionality.

**Comment by abe33** [comment]
I think we can even extend that to any change of that setting, so basically observing the setting and trigger the notification whenever we see it becoming true (given observing a setting mean getting notified on startup as well).
