### ISSUE TITLE
misleading signature rendering for kwarg with no examples

### ISSUE THREAD

**Issue by metalogical** [kiteco/atom-plugin#538]
![screen shot 2018-11-28 at 10 59 31 am](https://user-images.githubusercontent.com/1977419/49175199-e1df7a80-f2fc-11e8-91a4-24ebfe35b844.png)

`custom` in the first shown signature is a keyword argument, not positional. The API response does indicate that it is a kwarg (although the `examples` field is null, which is probably why it's rendered this way).

I'd propose always at least showing `custom=...` to make it clear. The copilot shows `custom=NoneType` which is more clear, but even better would be `custom: NoneType=...`.

@dhung09

**Comment by dbratz1177** [comment]
<img width="511" alt="screen shot 2019-02-26 at 5 28 46 pm" src="https://user-images.githubusercontent.com/6146901/53458710-07f3e400-39ec-11e9-9890-1d1075a15ffd.png">
This is what I'm getting currently
