### ISSUE TITLE
Status panel not closing when kite is started from the panel

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#541]
Seen on windows 10
I was testing #537 and started kite from the status panel. Kite did startup but the spinner wasn't stopping and I'm unable to close the panel.  Clicks on the background don't have any effect.

![screenshot_20181129_172835](https://user-images.githubusercontent.com/11473063/49236354-34539080-f3fc-11e8-9d1f-523340890ee9.png)

**Comment by dbratz1177** [comment]
fixed by https://github.com/kiteco/kite-connect-js/pull/12
