### ISSUE TITLE
Unable to save files when kite is enabled

### ISSUE THREAD

**Issue by mckeown12** [kiteco/atom-plugin#542]
https://github.com/atom/atom/issues/18114

**Comment by eric4867** [comment]
Can confirm this is happening for me as well

**Comment by falcoso** [comment]
Just started happening with me too. Have not had any updates or changes to my OS or atom extensions in the last 24hrs but it has just stopped saving files and also allowing me to use atom-python-run package.

Disabling package fixes the issue, have tried uninstall and reinstalling Kite extension and the Kite software but neither have helped.

Windows 10
Atom 1.33.0

**Comment by shiveringbulbul** [comment]
me, too

env: windows server 2008 R2
every file end with ".py" cannot save till turn off kite
but others are fine

**Comment by obarbier** [comment]
for me too

**Comment by obarbier** [comment]
I change the following line 
`    subs.add(editor.getBuffer().onWillSave(() => {
      if (!Kite) { Kite = require('./kite'); }
      if (Kite.isEditorWhitelisted(this.editor)) {
        return this.willSaveHook();
      }
      return null;
    }));`

to 
`    subs.add(editor.getBuffer().onWillSave(() => {
      if (!Kite) { Kite = require('./kite'); }
      return this.willSaveHook();
    }));
  }`
Solve the issue for me

**Comment by dhung09** [comment]
Hi guys, we're taking a look at this. We'll update as soon as we have more information / have a fix.

**Comment by dhung09** [comment]
This has been fixed. Please make sure you're on `v0.125.0`. Apologies for the inconvenience!
