### ISSUE TITLE
Documentation not rendered properly in tooltip

### ISSUE THREAD

**Issue by surdu** [kiteco/atom-plugin#56]
The documentation is rendered in plain text, missing all formatting.

As seen in Kite:
![screen shot 2017-02-10 at 17 25 31](https://cloud.githubusercontent.com/assets/11520795/22832248/fcb58ea4-efb5-11e6-9c88-efbb234b0579.png)

As seen in Atom:
![screen shot 2017-02-10 at 17 23 21](https://cloud.githubusercontent.com/assets/11520795/22832257/074e4126-efb6-11e6-9a94-488bd67b21a8.png)

**Comment by jlozano** [comment]
@abe33 can we close this?
