### ISSUE TITLE
Uncaught TypeError: KiteAPI.onDidDetectWhitelistedPath is not a function

### ISSUE THREAD

**Issue by TKassis** [kiteco/atom-plugin#562]
**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [kite](https://github.com/kiteco/atom-plugin) package 0.138.0

### Stack Trace

Uncaught TypeError: KiteAPI.onDidDetectWhitelistedPath is not a function

```
At C:\Users\Timothy\.atom\packages\kite\lib\editors.js:57

TypeError: KiteAPI.onDidDetectWhitelistedPath is not a function
    at KiteEditors.init (/packages/kite/lib/editors.js:57:36)
    at modulesToActivate.forEach.mod (/packages/kite/lib/kite.js:53:49)
    at Array.forEach (<anonymous>)
    at requestAnimationFrame (/packages/kite/lib/kite.js:53:30)
```

### Commands

```
```

### Non-Core Packages

```
kite 0.138.0 
```

**Comment by its-dhung** [comment]
Hi @TKassis, this has been fixed - please update the Kite package to `0.139.0`. Apologies for the inconvenience!
