### ISSUE TITLE
Mixpanel events still inconsistent on new installs

### ISSUE THREAD

**Issue by keien** [kiteco/atom-plugin#57]
On acp  1.8.50 and kite 0.8.7, I'm observing the following:
- during installation, I'm seeing `atom acp` type events (for example `atom acp - account created`) instead of `atom kite+acp` - not sure if this is intentional but I've seen both on Mixpanel so I want to know which ones are the ones we're sticking with
- immediately after installation, I only get events of the form `atom kite+acp - used completion not returned by Jedi` or `atom kite+acp - used completion returned by Jedi`, missing the `returned by Kite but also` part (`returned by` when not whitelisted, `not returned by` when whitelisted)
- in addition, no `Atom shows completions...` events are shown
- once Atom is restarted, the above issues are fixed and completions correctly send the full event name, as well as completions shown events; however, the atom console no longer shows logs for mixpanel events

**Comment by abe33** [comment]
For the first point, it's because the kite plugin isn't installed yet so the tracker is set on acp only. For the rest, that's because while the tracker name was changed the newly installed kite plugin wasn't patched so that acp can analyse which suggestions were provided.
