### ISSUE TITLE
Kite

### ISSUE THREAD

**Issue by 9994444ggg** [kiteco/atom-plugin#589]
Thank you very mutch

**Comment by its-dhung** [comment]
HI @9994444ggg, please let us know if you have issues with this plugin or Kite in general. Going to close this for now.

**Comment by 9994444ggg** [comment]
To Kite from@999444ggg helps me wonderfullhave some problems but it works day to day better.
Nice to write me.

**Comment by 9994444ggg** [comment]
Iam not a Professiona programmer but i like Kite ist wonderfull Extension to my Atom pack installation

**Comment by 9994444ggg** [comment]
No Kite is only for installing my Atom pack
