### ISSUE TITLE
Windows 10 shown as "not supported"

### ISSUE THREAD

**Issue by jansorg** [kiteco/atom-plugin#604]
With the current Kite release I saw this today:

![Screenshot_20190516_164738](https://user-images.githubusercontent.com/11473063/57863429-5e5a0d00-77fa-11e9-89e1-a1660f33684e.png)

**Comment by adamsmith** [comment]
We should just drop the version check for Windows users. Almost zero devs use XP or Vista.

**Comment by dbratz1177** [comment]
Try rechecking with the latest `kite-connect` release - https://github.com/kiteco/kite-connect-js/pull/25 should address the screenshot issue

**Comment by jansorg** [comment]
The latest release was working fine for me here.
