### ISSUE TITLE
'module' link doesn't work on expand ui (top-right)

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#63]
![feb-15-2017 20-04-51](https://cloud.githubusercontent.com/assets/87728/23006981/0fb24120-f3ba-11e6-8026-d10247cae8de.gif)

**Comment by abe33** [comment]
Yes, but it's because kited give us a 404 for `/api/editor/value/__builtin__.module`.

**Comment by jlozano** [comment]
@abe33 can we close this issue?
