### ISSUE TITLE
Auto-complete with multi-cursor completes only the last cursor

### ISSUE THREAD

**Issue by zaccharieramzi** [kiteco/atom-plugin#632]
When I am using auto-complete with multi-cursor, I found occurrences where only the last word is auto-completed (when pressing `enter`).

I have not identified a pattern and therefore cannot provide the steps for a reproducing example, sorry about that.

**Comment by metalogical** [comment]
Thanks @zaccharieramzi 

The fix here is to disable Kite completions in Atom when multiple cursors exist, since Kite has no way of sensibly computing completions. We're probably currently choosing one of the cursors to request completions.
