### ISSUE TITLE
"Kite cannot run on your computer !"

### ISSUE THREAD

**Issue by MAHDIJOMHOORI** [kiteco/atom-plugin#647]
![Screenshot (68)](https://user-images.githubusercontent.com/51445823/73928913-c371f900-4888-11ea-9670-76f967fe3d20.png)

**Comment by metalogical** [comment]
The error message explains the issue here: your machine does not satisfy Kite's minimum system requirements.

Unfortunately we have no plan to support non-AVX systems in the foreseeable future.

**Comment by MAHDIJOMHOORI** [comment]
I'm upset 😓
