### ISSUE TITLE
Kite engine still running after atom closes

### ISSUE THREAD

**Issue by matbeseris** [kiteco/atom-plugin#651]
Has anyone noticed that the Kite engine process stays running even after Atom closes? On a mac running Catalina, if you just open Atom and quit it, open Activity Monitor, you can see Kite Engine still running in the background (under the first 3 tabs I found it, but its easiest to find under Energy)

Not sure if this is an issue with kite or atom, but does anyone know how to fix it?

**Comment by metalogical** [comment]
Hi @matbeseris 

The Kite engine is not like a typical language server. It is not tied to a specific editor session, and it powers Kite in all of the editors you may use. If Atom were to quit Kite for you, this would be a poor experience for those who use Kite in multiple editors.

If you would like to quit Kite, you can enable the system tray icon (from the settings screen in the Kite Copilot), and there will be a menu in your system tray that gives you the option to quit.

Please let us know if you have other questions.

**Comment by matbeseris** [comment]
Gotcha! Thanks for the clarification, I understand now why it does this!
