### ISSUE TITLE
npm ERR! code Z_BUF_ERROR npm ERR! errno -5 npm ERR! zlib: unexpected end of file  npm ERR! A complete log of this run can be found in:

### ISSUE THREAD

**Issue by northeast250** [kiteco/atom-plugin#679]
0 info it worked if it ends with ok
1 verbose cli [ '/Applications/Atom.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/admin/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/admin/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/kite/versions/0.185.0/tarball',
1 verbose cli   '--target=5.0.13',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style' ]
2 info using npm@6.14.5
3 info using node@v10.20.1
4 verbose npm-session d071423b45d785ec
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/kiteco/atom-plugin/legacy.tar.gz/v0.185.0 3713ms (from cache)
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/kite/versions/0.185.0/tarball zlib: unexpected end of file
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 3734ms
11 verbose stack ZlibError: zlib: unexpected end of file
11 verbose stack     at Unzip.write (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:147:22)
11 verbose stack     at Unzip.flush (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:98:10)
11 verbose stack     at Unzip.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/minizlib/index.js:104:10)
11 verbose stack     at Object.end (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/tar/lib/parse.js:421:21)
11 verbose stack     at PassThrough.onend (_stream_readable.js:672:10)
11 verbose stack     at Object.onceWrapper (events.js:286:20)
11 verbose stack     at PassThrough.emit (events.js:203:15)
11 verbose stack     at endReadableNT (_stream_readable.js:1145:12)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
12 verbose cwd /private/var/folders/0k/85mwpxr57174qlj_1rp3vfdh0000gq/T/apm-install-dir-2020516-37455-mum8ma.2hcym
13 verbose Darwin 19.5.0
14 verbose argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/admin/.atom/.apm/.apmrc" "--userconfig" "/Users/admin/.atom/.apmrc" "install" "https://www.atom.io/api/packages/kite/versions/0.185.0/tarball" "--target=5.0.13" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
15 verbose node v10.20.1
16 verbose npm  v6.14.5
17 error code Z_BUF_ERROR
18 error errno -5
19 error zlib: unexpected end of file
20 verbose exit [ -5, true ]

**Comment by its-dhung** [comment]
This is probably unrelated to Kite. [This thread may be useful](https://discuss.atom.io/t/unable-to-install-any-atom-package/71899).
