### ISSUE TITLE
Unable to get a student license

### ISSUE THREAD

**Issue by sayedsadat98** [kiteco/atom-plugin#695]
Greetings Kite team,
Kite is an excellent code completion software and i want to use it with pycharm IDE. I tried to get an educational license but when i click on ACTIVATE button on the website (https://www.kite.com/pro/student/) it doesn't work. Can anyone guide me how to get that ?

Thanks

**Comment by metalogical** [comment]
duplicate of https://github.com/kiteco/issue-tracker/issues/354
