### ISSUE TITLE
Broken flow when directly installing kite plugin

### ISSUE THREAD

**Issue by keien** [kiteco/atom-plugin#70]
cc @adamsmith 
this is what it looks like after installing kite plugin into a fresh machine without Kite app
![screen shot 2017-02-16 at 7 52 00 pm](https://cloud.githubusercontent.com/assets/1103512/23051982/2576d174-f482-11e6-928c-9f7e52ff5fd7.png)

**Comment by adamsmith** [comment]
(It looks like the styling/js/something isn't working, and the notification.)

**Comment by abe33** [comment]
Right... Aside from the CSS stuff, which is easy to fix, I assumed that the installer was working properly without much setup, but it appears that it's not the case. I'll look for an easy fix and then I'll probably have to take some time next week to review the installer stuff (which I had suggested at some point, but never took the time to tackle) and make it really independent.

**Comment by adamsmith** [comment]
Okay, thanks Cedric!

**Comment by keien** [comment]
confirmed fixed
