### ISSUE TITLE
Hover view should only appear on mouse hover

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#71]
If I move my cursor over a token and keep it there, the hover UI appears.  I believe it should only appear if my mouse hovers over the token.

**Comment by abe33** [comment]
It's easy to fix, but do we want to have only hints available through mouse interactions? A lot of developers are striving for keyboard-only interactions.

**Comment by adamsmith** [comment]
I agree that it's important to have everything accessible via the keyboard, but for this narrow case I think we only want it to be triggered via the mouse, because "hovering" the cursor is such a common thing.  For keyboard-only users, I think the main option for them will be Cmd+D to select the token and see the expand panel.
