### ISSUE TITLE
Changing plugin settings not saved (embed codefinder decoration)

### ISSUE THREAD

**Issue by zilbert97** [kiteco/atom-plugin#722]
In Atom, deselecting the "embed codefinder decoration" setting is not being saved.
- Deselecting the option changes the setting for the current window, but any other windows opened will have this setting re-enabled.
- When de-selecting this setting, closing Atom, and re-opening, the setting is re-enabled. I have tried re-launching Atom with safe-mode but the issue persists, and after launching in safe mode re-closing and re-opening Atom (in standard mode) still has the issue.
- Within the same window and session (booted in normal mode), deselect this setting, disable kite, and re-enable kite - the setting is automatically re-selected.

Details:
- Kite plugin for Atom - 0.203.0
- Atom - 1.54.0

https://user-images.githubusercontent.com/61543475/108504440-c67e3280-72ad-11eb-933e-39f5f38a0c8c.mov

**Comment by vincentrose88** [comment]
Can verify I have the same issue, and I feel like I've tried everything, even making the `config.cson` not writable. Now I'm ready to throw in the towel, and hope this will be fixed.

Details:
- Atom 1.54.0
- Kite package 0.203.0
- MacOS Big Sur 11.2.1

**Comment by tonycheang** [comment]
Thanks for the bug report. We released a new version (`v0.200.4`) just now that should persist the setting. Please update and if you're still experiencing this, re-open or leave a comment and I can take another look.
