### ISSUE TITLE
Showing expand panel after selecting a completion

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#75]
After a user selects a completion we shouldn't show the expand panel.  (and this also breaks the pattern of only showing the expand panel when a token is selected.)

![feb-23-2017 10-02-56](https://cloud.githubusercontent.com/assets/87728/23272286/7d387dc2-f9af-11e6-880f-8aed92e0623c.gif)

**Comment by abe33** [comment]
It looks like a duplicate of #41

**Comment by adamsmith** [comment]
Yes, looks like it, thanks.
