### ISSUE TITLE
Incorrect locator/path used for local code jump-to-web link

### ISSUE THREAD

**Issue by tarakju** [kiteco/atom-plugin#76]
Clicking on "Open in Web" on a class in the current file results in the following. Note the lack of `SnippetExtractor` referenced in the URL. Currently unsure whether this is an issue with what the backend is returning or whether the plugin is constructing the URL incorrectly.

![screenshot 2017-02-22 17 34 32](https://cloud.githubusercontent.com/assets/5125230/23276790/8528f23a-f9c0-11e6-9bfe-056ad4609266.png)

**Comment by abe33** [comment]
@tarakju I think it comes from the backend, I'm using the following code to construct the url: 

```js
function openDocumentationInWebURL(id) {
  const token = StateController.client.LOCAL_TOKEN;
  return `http://localhost:46624/clientapi/desktoplogin?d=/docs/python/${id}&localtoken=${token}`;
}
```
https://github.com/kiteco/atom-plugin/blob/master/lib/urls.js#L67-L70

Where `id` is the id received in the response with no transformations.

**Comment by alexflint** [comment]
Yeah this is a backend issue. Will move to a different issue tracker.
