### ISSUE TITLE
Atom plugin not activating

### ISSUE THREAD

**Issue by krutaw** [kiteco/atom-plugin#77]
Greetings,

I'm continually receiving a message in the sidebar stating that the Atom plugin has been installed but that it needs to be restarted to receive events.  I'm not seeing any options to restart the plugin in the tool.  I've attempted restarting both Atom and Kite as well as the machine in question.  Thoughts?

**Comment by adamsmith** [comment]
Interesting!  Can you try opening/saving a `.py` file in Atom, typing some character, and see if it goes away then?

Thanks for the info!

**Comment by krutaw** [comment]
That got 'er. :)
