### ISSUE TITLE
Add Mixpanel event for "used Kite completion"

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#8]

**Comment by alexflint** [comment]
This is already in: https://github.com/kiteco/atom-plugin/blob/master/lib/completions.js#L83

I have not tested it recently though - could be not working for some reason. If you open the console while inserting a Kite suggestion then you should see `event: suggestion used` printed.

**Comment by adamsmith** [comment]
It appears that these events happen for both Jedi and Kite completions.  Ideally we'd have three event types:

* jedi-only completion selected (kite didn't return the completion)
* kite-only completion selected
* jedi+kite completion selected (completion was provided by Jedi and Kite)

**Comment by adamsmith** [comment]
Added by Cedric.
