### ISSUE TITLE
breadcrumbs in expand UI can get arbitrarily long

### ISSUE THREAD

**Issue by alexflint** [kiteco/atom-plugin#85]
It is possible to navigate arbitrarily far inside the expand UI, e.g. I can keep clicking on "type" here forever:

![screenshot 2017-02-27 17 07 40](https://cloud.githubusercontent.com/assets/640247/23387100/4d0b8ae6-fd0f-11e6-9f05-46305659c283.png)

I'm not exactly sure what to do about breadcrumbs in this case but just wanted to flag this up as something to watch out for.

**Comment by jlozano** [comment]
@abe33 I think it is safe to close this for now
