### ISSUE TITLE
"Open in Web" looks odd in Atom Light / One Light theme

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#93]
![screen shot 2017-03-02 at 3 33 13 pm](https://cloud.githubusercontent.com/assets/87728/23531928/b98d361a-ff5d-11e6-8d4e-9b08e3a95e8a.png)

![screen shot 2017-03-02 at 3 34 33 pm](https://cloud.githubusercontent.com/assets/87728/23531932/bf9b4826-ff5d-11e6-91fb-2f03264bf529.png)

**Comment by abe33** [comment]
FWIW the proper default combination is `one light` for boths, or `atom light` for both.

`Atom light` and `Atom dark` was the initial default from 3 years ago, `One light` and `One dark` became the default after that.

Anyway, we should not rely on `selected` theme variables to avoid this kind of issue.
