### ISSUE TITLE
Sidebar should be resizable

### ISSUE THREAD

**Issue by adamsmith** [kiteco/atom-plugin#95]
If I move my cursor along the left edge of the sidebar I should see a horizontal resize cursor and be able to resize the sidebar.  Ideally the size would have some minimum, and be saved across sessions.

**Comment by abe33** [comment]
That's already the case: 

![kite-resize-sidebar](https://cloud.githubusercontent.com/assets/247140/23586943/2bca7c34-01a1-11e7-95cf-e0365dd89084.gif)

**Comment by alexflint** [comment]
Awesome.
