### ISSUE TITLE
Module label in hover UI shouldn't look interactive

### ISSUE THREAD

**Issue by abmirayo** [kiteco/atom-plugin#96]
@abe33 

Currently the "module" label we show on modules shows `cursor: pointer` and `text-decoration: underline` when hovering. 

Do you know if there are instances where it *should* be interactive? (As in, it shows a token we can resolve or go to?) If there are, we should just make the "module" label non-interactive, and other labels of types that do work interactive.

![image](https://cloud.githubusercontent.com/assets/163122/23532557/dcf58b4a-ff60-11e6-8c5a-b1484d99f8d4.png)

**Comment by abe33** [comment]
This is basically the same links than what we have in the expanded views. It's technically possible to trigger something when clicking on them, but we'll suffer from the same issues than the expand view, that is we can't know if there's data available until we try. For the time being I'll disable these links.
