### ISSUE TITLE
Maintain text position when resizing side panel

### ISSUE THREAD

**Issue by alexflint** [kiteco/atom-plugin#99]
To reproduce: open the side panel to show multiple screenfulls of information, then scroll down to near the bottom and resize the panel. The "reading position" is lost as the text scrolls by.

Ideally the viewport would be anchored to the top line of text while the side panel is resized.

I imagine this might be complicated to implement, in which case this is a fairly low-priority issue.

![](http://g.recordit.co/rolwKXfaM6.gif)

**Comment by abe33** [comment]
Not sure how this can be solved, I know we can get the position of some text as long as we know its char range but I don't know how to get the range based on the scroll, it'll require some deeper search before I can tell how complex it'll be to implement.

**Comment by rodriguezmanu** [comment]
+1

**Comment by jansorg** [comment]
Closing, as it's old and not planned at this time.
